- CHANGELOG.md
- src/index.react-native.ts
- src/types/ambient.d.ts
polyfills missing globals for React Native environments.
(Check _one!_)
- Fixes #62 
None.
> Polyfill certain globals for React Native

- CHANGELOG.md
- src/modules/rpc-provider/index.ts
- src/util/url.ts
(Check _one!_)
- Fixes #76 
- Fixes #71
> Fix URL constructor bug for Safari

- README.md
Remove vulnerabilities badges
(Check _one!_)
None of the above. It is a README update
- #73 
None.
Don't need to update changelog. It is README update.
> Remove vulnerabilities badge

- CHANGELOG.md
- src/types/modules/rpc-provider-types.ts
(Check _one!_)
- Fixes #81 
No special test cases here, just run `yarn test`.
> Add 'EthChainType' enum & 'CustomNodeConfiguration.chainType' interface

- src/index.react-native.ts
We had a bug in React Native that caused a `can't find variable: Buffer`. This should fix that 😄 
(Check _one!_)
`yarn test`
> Update React Native entry-point to resolve undefined 'Buffer' bug

- CHANGELOG.md
- README.md
CircleCI badge correction in README
- Fixes [#99](https://github.com/magiclabs/magic-js/issues/99#issue-627513141)
No testing necessary.
> Patch Update README [#99]

- packages/react-native/CHANGELOG.md
- packages/react-native/package.json
(Check _one!_)
Move `react-native-webview` from dependency to peer dependency to resolve IOS building module conflict
Fix #91 
Test with local built library
- [*] I have updated the `Upcoming Changes` section of `CHANGELOG.md` with context related to this Pull Request.
> Remove react-native-webview dependencies

- CONTRIBUTING.md
- package.json
- packages/provider/CHANGELOG.md
- packages/provider/package.json
- packages/provider/src/core/sdk-exceptions.ts
- packages/provider/src/modules/base-extension.ts
- packages/provider/src/modules/base-module.ts
- packages/provider/test/spec/core/sdk-exceptions/magic-extension-error/constructor.spec.ts
- packages/provider/test/spec/modules/base-extension/init.spec.ts
- packages/provider/test/spec/modules/base-extension/raiseError.spec.ts
- packages/react-native/CHANGELOG.md
- packages/react-native/package.json
- packages/react-native/src/index.ts
- packages/react-native/test/factories.ts
- packages/react-native/test/mocks.ts
- packages/react-native/test/setup.ts
- packages/react-native/test/spec/index.spec.ts
- packages/react-native/test/spec/react-native-sdk-base/Relayer.spec.ts
- packages/web/CHANGELOG.md
- packages/web/package.json
- packages/web/src/index.cdn.ts
- packages/web/src/index.ts
- scripts/clean.sh
- scripts/test.sh
- yarn.lock
- Introduces a new error type: `ExtensionError`, exposed to offer a consistent error interface for upcoming Magic SDK Extensions.
- Adds a `raiseError` method to the `BaseExtension` module, offering a quick way to raise `ExtensionError`s
(Check _one!_)
`yarn test`
> Framework for Magic SDK Extension errors

- packages/provider/src/modules/base-extension.ts
- packages/provider/src/util/query-params.ts
- packages/provider/test/spec/modules/base-extension/constructor.spec.ts
- packages/provider/test/spec/util/queryParams.spec.ts
Adds a few new utilities to the `Extension` base class & organizes all utilities under the `utils` field.
(Check _one!_)
> Expose more utils on the 'Extension' base class

- packages/provider/CHANGELOG.md
- packages/provider/src/core/sdk-exceptions.ts
- packages/provider/src/core/sdk.ts
- packages/provider/src/modules/base-extension.ts
- packages/provider/src/util/base64-json.ts
- packages/provider/src/util/index.ts
- packages/provider/src/util/query-params.ts
- packages/provider/test/spec/core/sdk-exceptions/magic-extension-warning/constructor.spec.ts
- packages/provider/test/spec/core/sdk-exceptions/magic-extension-warning/log.spec.ts
- packages/provider/test/spec/core/sdk-exceptions/warning-factories.spec.ts
- packages/provider/test/spec/modules/base-extension/constructor.spec.ts
- packages/provider/test/spec/modules/base-extension/createDeprecationWarning.spec.ts
- packages/provider/test/spec/modules/base-extension/createWarning.spec.ts
- packages/provider/test/spec/util/base64JSON.spec.ts
- packages/react-native/CHANGELOG.md
- packages/react-native/src/index.ts
- packages/types/CHANGELOG.md
- packages/types/src/core/exception-types.ts
- packages/web/CHANGELOG.md
- packages/web/src/index.cdn.ts
- packages/web/src/index.ts
- packages/web/test/spec/helloWorld.spec.ts
- Add `MagicExtensionWarning`
- Add `SDKWarningCode.DeprecationNotice` along with standard methods for communicating deprecations
- Add `encodeJSON` and `decodeJSON`, mark `encodeQueryParameters` and `decodeQueryParameters` for deprecation.
(Check _one!_)
> Add Extension warnings and deprecation notices

- packages/types/.babelrc
- packages/types/CHANGELOG.md
- packages/types/src/core/exception-types.ts
- packages/types/src/core/json-rpc-types.ts
- packages/types/src/modules/auth-types.ts
- packages/types/src/modules/user-types.ts
Types for WebAuthn support
(Check _one!_)
N/A
No tests for types
> Webauthn support types

- packages/provider/CHANGELOG.md
- packages/react-native/CHANGELOG.md
- packages/types/CHANGELOG.md
- packages/types/src/core/exception-types.ts
- packages/web/CHANGELOG.md
Adds a new error code to the `RPCErrorCode` enum from `@magic-sdk/types`. This will constitute a patch upgrade for every package in the repo.
(Check _one!_)
> Add `-10005` error code to `RPCErrorCode` enum

- packages/provider/CHANGELOG.md
- packages/provider/src/core/sdk.ts
- packages/provider/test/spec/core/sdk/constructor.spec.ts
- packages/react-native/CHANGELOG.md
- packages/types/src/core/query-types.ts
- packages/web/CHANGELOG.md
Added locale flag to SDK constructor
(Check _one!_)
> add local flag to query param object

- README.md
Add testing guide
(Check _one!_)
> add test Testing Guide

- .circleci/config.yml
- .gitignore
- package.json
- yarn.lock
Adds [`auto`](https://github.com/intuit/auto) for CI releases.
> Add 'auto' for CI release

- README.md
Testing auto-release on `next` branch
> Test auto-release

- .circleci/config.yml
- CONTRIBUTING.md
- package.json
- Remove `git push` part of the flow (apparently `auto` will update base branch versions automatically)
> Auto: CI adjustments

- packages/provider/src/core/sdk.ts
Add list of newly-supported i18n languages.
> Improve i18n Support

- .circleci/config.yml
> update yml comment for cirle ci

- packages/@magic-sdk/provider/src/core/payload-transport.ts
- packages/@magic-sdk/provider/test/spec/core/payload-transport/post.spec.ts
Ignore calling webcrypto apis if not web platform
> bypass webcrypto on non web platforms

- packages/@magic-sdk/react-native/src/index.ts
- packages/magic-sdk/src/index.ts
> Update next branch

- packages/@magic-sdk/pnp/src/context/login.ts
- packages/@magic-sdk/pnp/src/pnp-extension.ts
- packages/@magic-sdk/pnp/src/utils/script-data.ts
- yarn.lock
This PR adds support for `data-terms-of-service-uri` and `data-privacy-policy-uri` to the Magic Login Form script tag created by `@magic-sdk/pnp`.
> Add parameters for ToS and privacy links to `@magic-sdk/pnp`

- packages/@magic-ext/conflux/.eslintignore
- packages/@magic-ext/conflux/.eslintrc.js
- packages/@magic-ext/conflux/.lintstagedrc.yml
- packages/@magic-ext/conflux/.prettierrc.js
- packages/@magic-ext/conflux/LICENSE
- packages/@magic-ext/conflux/package.json
- packages/@magic-ext/conflux/src/index.cdn.ts
- packages/@magic-ext/conflux/src/index.native.ts
- packages/@magic-ext/conflux/src/index.ts
- packages/@magic-ext/conflux/src/types.ts
- packages/@magic-ext/conflux/tsconfig.json
- yarn.lock
Adds `@magic-ext/conflux` extension.
> magic-conflux extension

- .circleci/config.yml
- packages/@magic-ext/solana/src/index.native.ts
This PR fixes the export of the index file to not have react native think that the file is referencing itself. 
Fixes #265 
See if `Magic` object can be initialized correctly in a react native application
- `patch`: Bug Fix
> Fixing solana react native

- CONTRIBUTING.md
- package.json
- scripts/bin/build.ts
- scripts/bin/dev.ts
- scripts/bin/wsrun/build-package.ts
- scripts/utils/environment.ts
- scripts/utils/esbuild.ts
- scripts/utils/workspace-helpers.ts
- yarn.lock
Adds a `dev` script to improve the internal developer experience of `magic-js` packages.
> Add 'dev' script

- packages/@magic-ext/flow/src/index.ts
- packages/@magic-ext/flow/src/type.ts
- add flow domain tag feature support
- `minor`: New Feature
> Add flow domain tag feature support

- packages/@magic-ext/cosmos/src/index.ts
- packages/@magic-ext/cosmos/src/type.ts
- yarn.lock
Add cosmos change address function
- `minor`: Add cosmos change address function
> Add cosmos change address function

- packages/@magic-ext/terra/.eslintignore
- packages/@magic-ext/terra/.eslintrc.js
- packages/@magic-ext/terra/.lintstagedrc.yml
- packages/@magic-ext/terra/.prettierrc.js
- packages/@magic-ext/terra/LICENSE
- packages/@magic-ext/terra/package.json
- packages/@magic-ext/terra/src/index.cdn.ts
- packages/@magic-ext/terra/src/index.native.ts
- packages/@magic-ext/terra/src/index.ts
- packages/@magic-ext/terra/src/types.ts
- packages/@magic-ext/terra/tsconfig.json
- yarn.lock
> terra support

- packages/@magic-ext/taquito/.eslintignore
- packages/@magic-ext/taquito/.eslintrc.js
- packages/@magic-ext/taquito/.lintstagedrc.yml
- packages/@magic-ext/taquito/.prettierrc.js
- packages/@magic-ext/taquito/LICENSE
- packages/@magic-ext/taquito/package.json
- packages/@magic-ext/taquito/src/MagicSinger.ts
- packages/@magic-ext/taquito/src/SignerInterface.ts
- packages/@magic-ext/taquito/src/index.cdn.ts
- packages/@magic-ext/taquito/src/index.native.ts
- packages/@magic-ext/taquito/src/index.ts
- packages/@magic-ext/taquito/src/type.ts
- packages/@magic-ext/taquito/tsconfig.json
- yarn.lock
> taquito support

- packages/@magic-sdk/provider/src/modules/auth.ts
- packages/@magic-sdk/provider/test/spec/modules/auth/loginWithCredential.spec.ts
- packages/@magic-sdk/provider/test/spec/modules/auth/loginWithEmailOTP.spec.ts
- packages/@magic-sdk/provider/test/spec/modules/auth/loginWithMagicLink.spec.ts
- packages/@magic-sdk/provider/test/spec/modules/auth/loginWithSms.spec.ts
- packages/@magic-sdk/types/src/core/json-rpc-types.ts
- packages/@magic-sdk/types/src/modules/auth-types.ts
- Adds `loginWithEmailOTP` support to magic js sdk
- https://app.shortcut.com/magic-labs/story/49718/dx-add-loginwithemailotc-support-to-magic-js-sdk
> [Chore]: added `loginWithEmailOTP` method

- packages/@magic-ext/conflux/src/index.ts
- packages/@magic-ext/conflux/src/types.ts
- yarn.lock
Update the constructor to just have the developer pass in the rpc url and networkId
> update conflux constructor

- packages/@magic-sdk/provider/src/core/sdk-environment.ts
- packages/@magic-sdk/provider/src/core/sdk.ts
- packages/@magic-sdk/provider/test/spec/core/sdk/constructor.spec.ts
- packages/@magic-sdk/react-native/jest.config.ts
- packages/@magic-sdk/react-native/package.json
- packages/@magic-sdk/react-native/src/index.ts
- packages/@magic-sdk/types/src/core/query-types.ts
- yarn.lock
Reverts magiclabs/magic-js#335
To re-trigger CI
> Revert "Enable bundle Id in Expo"

- packages/@magic-sdk/provider/src/core/sdk-environment.ts
- packages/@magic-sdk/provider/src/core/sdk.ts
- packages/@magic-sdk/provider/test/spec/core/sdk/constructor.spec.ts
- packages/@magic-sdk/react-native/jest.config.ts
- packages/@magic-sdk/react-native/package.json
- packages/@magic-sdk/react-native/src/index.ts
- packages/@magic-sdk/types/src/core/query-types.ts
- yarn.lock
Reverts magiclabs/magic-js#337
> Revert "Revert "Enable bundle Id in Expo""

- packages/@magic-ext/ed25519/.eslintignore
- packages/@magic-ext/ed25519/.eslintrc.js
- packages/@magic-ext/ed25519/.lintstagedrc.yml
- packages/@magic-ext/ed25519/.prettierrc.js
- packages/@magic-ext/ed25519/LICENSE
- packages/@magic-ext/ed25519/package.json
- packages/@magic-ext/ed25519/src/index.cdn.ts
- packages/@magic-ext/ed25519/src/index.native.ts
- packages/@magic-ext/ed25519/src/index.ts
- packages/@magic-ext/ed25519/src/types.ts
- packages/@magic-ext/ed25519/tsconfig.json
- yarn.lock
> add @magic-ext/ed25519

- packages/@magic-ext/connect/package.json
- packages/@magic-ext/connect/src/index.ts
- yarn.lock
[Add Required Flag to requestUserInfo SDK method](https://app.shortcut.com/magic-labs/story/54489/add-required-flag-to-the-requestuserinfo-sdk-method)
- [Fixes #54489](https://app.shortcut.com/magic-labs/story/54489/add-required-flag-to-the-requestuserinfo-sdk-method)
> add options param to requestUserInfo

- packages/@magic-sdk/types/src/modules/rpc-provider-types.ts
- yarn.lock
> drop legacy testnet support

- packages/@magic-ext/connect/src/index.ts
- packages/@magic-ext/connect/src/types.ts
- yarn.lock
Adds new method `getWalletInfo()` which returns an object with the wallet type that the user is logged in with (`magic`, `metamask`, `wallet_connect` or `coinbase_wallet`)
> add getWalletInfo method

- CHANGELOG.md
- packages/@magic-ext/oauth/CHANGELOG.md
> Update CHANGELOG.md [skip ci]

- README.md
- packages/@magic-sdk/react-native/README.md
A user ran into an obscure symlink error when installing our RN SDK. This adds a Troubleshooting section to the README's and some advice that could help anyone else that runs into this error. 
n/a
n/a
> Adds advice for fixing symlink error in RN projects inside of Monorepos to README

- packages/@magic-ext/solana/src/index.ts
Deprecate `sendAndConfirmTransaction` for @magic-ext/solana as it is no longer supported.
> Deprecate sendAndConfirmTransaction for @magic-ext/solana

- yarn.lock
> Update Yarn.lock file

- .github/workflows/publish.yml
- yarn.lock
This explicitly sets the build-output downloads path to `packages` since that's where the lerna packages are.
> [CHORE] extract build output files to packages directory

- .github/workflows/publish.yml
- packages/@magic-sdk/commons/README.md
- packages/@magic-sdk/provider/README.md
- packages/@magic-sdk/types/README.md
> Update Commons/Provider/Types Packages + Workflow

- packages/@magic-sdk/react-native-bare/README.md
- packages/@magic-sdk/react-native-expo/README.md
- yarn.lock
Add link to RN Demo Apps to each SDK's READMEs
n/a
n/a
> Add link to RN Demo Apps to READMEs

- packages/@magic-ext/connect/README.md
Bump Version of `@magic-sdk/connect` to 6.2.0
n/a
n/a
> Bump Version of `@magic-sdk/connect` to 6.2.0

- packages/@magic-ext/connect/README.md
- packages/@magic-sdk/react-native-bare/README.md
- packages/@magic-sdk/react-native-expo/README.md
Bump Version of @magic-sdk/connect to 6.2.0
> Bump Version of @magic-sdk/connect to 6.2.0, Again

- .github/PULL_REQUEST_TEMPLATE.md
Updates PR Template to warn against multi label selection. 
n/a
n/a
> Updates PR Template warning about one label

- packages/@magic-sdk/provider/README.md
- packages/@magic-sdk/types/README.md
This happened again  https://fortmatic.slack.com/archives/C03AU5FMV5H/p1674611835730899 🤦 
n/a
n/a
> Update Package versions

- packages/@magic-sdk/provider/src/modules/nft.ts
- packages/@magic-sdk/provider/test/spec/modules/nft/airdrop.spec.ts
- packages/@magic-sdk/types/src/core/json-rpc-types.ts
> add nft airdrop method

- README.md
- packages/magic-sdk/README.md
Updating Readme to reflect latest methods and docs
> updated readme with new description and quickstart code sample

- yarn.lock
Update yarn.lock for recovery SDK released
> * Update yarn.lock

- packages/@magic-ext/flow/src/index.ts
- packages/@magic-ext/flow/src/type.ts
- yarn.lock
update ext to support flow MC 
- `minor`: support flow in MC
> flow getAccount and pass cadence in

- packages/@magic-sdk/provider/package.json
- yarn.lock
update types version in provider
> manually update types version in provider package

- packages/@magic-ext/flow/src/index.ts
- yarn.lock
Add optional chaining when the Flow account is not passed in.
> Calling magic flow authorization throws error [sc-74792]

- packages/@magic-sdk/types/src/core/message-types.ts
Adds `MAGIC_MG_BOX_SEND_RECEIPT` to `MagicIncomingWindowMessage` for new receipting system added to Relayer.
n/a
<details>
<br />
```bash
npm install @magic-ext/algorand@11.1.0-canary.490.4602563296.0
npm install @magic-ext/avalanche@11.1.0-canary.490.4602563296.0
npm install @magic-ext/bitcoin@11.1.0-canary.490.4602563296.0
npm install @magic-ext/conflux@9.1.0-canary.490.4602563296.0
npm install …
```
> Adds `MAGIC_MG_BOX_SEND_RECEIPT` to `MagicIncomingWindowMessage`

- packages/@magic-sdk/provider/src/modules/user.ts
- packages/@magic-sdk/provider/test/spec/modules/user/showSettings.spec.ts
- packages/@magic-sdk/types/src/core/deep-link-pages.ts
- packages/@magic-sdk/types/src/modules/user-types.ts
- yarn.lock
https://app.shortcut.com/magic-labs/story/75641/lazer-request-showsettings-page-mfa
> Jerryliu sc 75641 lazer request showsettings page mfa

- packages/@magic-ext/auth/src/index.ts
- packages/@magic-sdk/provider/src/modules/auth.ts
- yarn.lock
Custom Auth is missing jwt token in the payload
> quick fix passing authorization token in payload

- packages/@magic-sdk/commons/LICENSE
- packages/@magic-sdk/pnp/LICENSE
- packages/@magic-sdk/provider/LICENSE
- packages/@magic-sdk/react-native-bare/LICENSE
- packages/@magic-sdk/react-native-expo/LICENSE
- packages/@magic-sdk/types/LICENSE
- packages/magic-sdk/LICENSE
- yarn.lock
https://app.shortcut.com/magic-labs/story/75984/update-magic-sdk-license-to-apache-2-0
<details>
<br />
```bash
npm install @magic-ext/algorand@12.1.2-canary.500.4789316256.0
npm install @magic-ext/auth@0.2.2-canary.500.4789316256.0
npm install @magic-ext/avalanche@12.1.2-canary.500.4789316256.0
npm install @magic-ext/bitcoin@12.1.2-canary.500.4789316256.0
npm install …
```
> update MIT license to apache

- packages/@magic-sdk/react-native-expo/README.md
- yarn.lock
- Updates the installation instruction in the react native expo README: `webview@^8.0.0` to `webview@^11.0.0`
- Ticket: [SC-77511](https://app.shortcut.com/magic-labs/story/77511/update-readme-react-native-webview)
> update Webview version in README

- packages/@magic-sdk/types/src/core/json-rpc-types.ts
Sardine updated their API spec, so we need to adjust the SDK to submit the new required information.
Related Ticket: https://app.shortcut.com/magic-labs/story/77207/sardine-nft-purchase-secondary
> [FIX]: updates for Sardines new API spec

- packages/@magic-sdk/types/src/core/deep-link-pages.ts
- packages/@magic-sdk/types/src/modules/user-types.ts
- yarn.lock
https://app.shortcut.com/magic-labs/story/77755/kresus-hotfix
> Update getMetdata Type

- packages/@magic-ext/aptos/src/index.ts
- packages/@magic-ext/aptos/src/type.ts
- yarn.lock
- clean unused configs and support custom nodeUrl
- resolve pointing to `devnet` only
- https://app.shortcut.com/magic-labs/story/78463/aptos-refactor-aptos-config
<details>
<br />
```bash
npm install @magic-ext/aptos@0.4.0-canary.524.5073811608.0
yarn add @magic-ext/aptos@0.4.0-canary.524.5073811608.0
```
</details>
> Refactor aptos config

- packages/@magic-ext/aptos/src/MagicAptosWallet.ts
- packages/@magic-ext/aptos/src/index.ts
- packages/@magic-ext/aptos/src/type.ts
> Change MagicAptosWallet design and fix type mismatch issue

- packages/@magic-ext/aptos/.eslintrc.js
- packages/@magic-ext/aptos/babel.config.json
- packages/@magic-ext/aptos/jest.config.ts
- packages/@magic-ext/aptos/src/MagicAptosWallet.ts
- packages/@magic-ext/aptos/src/index.ts
- packages/@magic-ext/aptos/test/setup.ts
- packages/@magic-ext/aptos/test/spec/aptos-extension.spec.ts
- packages/@magic-ext/aptos/test/spec/magic-aptos-wallet.spec.ts
- packages/@magic-ext/aptos/test/tsconfig.json
updated
Add AptosExtension test suite
- scaffold test environment with `yarn scaffold`
Add aptos-extension.spec.ts
> Add test suites for Aptos and fix minor bugs

- packages/@magic-ext/aptos/test/spec/aptos-extension.spec.ts
- Minor changes for aptos testing
- To publish @magic-ext/aptos
- refactor duplicate variables
- Fix node URL 
> Minor changes for aptos testing

- packages/@magic-sdk/provider/src/modules/nft.ts
- packages/@magic-sdk/provider/test/spec/modules/nft/purchase.spec.ts
- packages/@magic-sdk/types/src/core/json-rpc-types.ts
> [FEAT]: adding types for nft checkout

- packages/@magic-ext/auth/src/index.ts
- packages/@magic-ext/auth/src/util/version-check.ts
- packages/@magic-sdk/commons/src/index.ts
- packages/@magic-sdk/provider/src/modules/auth.ts
- packages/@magic-sdk/provider/src/util/version-check.ts
- packages/@magic-sdk/react-native-bare/README.md
- packages/@magic-sdk/react-native-expo/README.md
- yarn.lock
To be released June 20th
n/a
<details>
<br />
```bash
npm install @magic-ext/algorand@13.0.0-canary.516.5326098666.0
npm install @magic-ext/aptos@1.0.0-canary.516.5326098666.0
npm install @magic-ext/auth@1.0.0-canary.516.5326098666.0
npm install @magic-ext/avalanche@13.0.0-canary.516.5326098666.0
npm install @magic-ext/bitcoin@13.0.0-canary.516.5326098666.0
npm install @magic-ext/conflux@11.0.0-canary.516.5326098666.0
npm install …
```
> Removes Magic link Method

- packages/@magic-sdk/react-native-expo/README.md
- packages/@magic-sdk/react-native-expo/package.json
- yarn.lock
Update Peer Dependency of Expo Package and README to denote compatible version of `react-native-webview`
n/a
n/a
> Update RN Expo Package README and Peer dependency

- jest.config.ts
> Revert Threshold Change

- packages/@magic-ext/gdkms/src/index.ts
- packages/@magic-ext/gdkms/test/spec/gdkms.spec.ts
Fix typos for relayer to pick up the requests params
> Fix typo for gdkms

- packages/@magic-ext/flow/package.json
- packages/@magic-ext/flow/src/index.ts
- yarn.lock
https://github.com/onflow/fcl-js/blob/8dcb70cbb197b0c4a0f131d2d282328612d98803/packages/fcl/CHANGELOG.md?plain=1#L1446C1-L1446C1
https://app.shortcut.com/magic-labs/story/80839/upgrade-flow-package
<details>
<br />
```bash
npm install @magic-ext/algorand@13.2.2-canary.563.5480923781.0
npm install …
```
> Upgrade @onflow/fcl

- packages/@magic-sdk/provider/src/modules/user.ts
- packages/@magic-sdk/provider/src/modules/wallet.ts
- yarn.lock
Persist webcrypto keys pair even after logout.
<details>
<br />
```bash
npm install @magic-ext/algorand@13.4.0-canary.562.5483003772.0
npm install @magic-ext/aptos@1.4.0-canary.562.5483003772.0
npm install @magic-ext/auth@1.4.0-canary.562.5483003772.0
npm install @magic-ext/avalanche@13.4.0-canary.562.5483003772.0
npm install @magic-ext/bitcoin@13.4.0-canary.562.5483003772.0
npm install …
```
> remove ClearKeys()

- packages/@magic-ext/react-native-bare-oauth/CHANGELOG.md
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/react-native-bare-oauth@13.4.2-canary.566.5491124788.0
yarn add @magic-ext/react-native-bare-oauth@13.4.2-canary.566.5491124788.0
```
</details>
> Changelog Update to RN-OAuth ext for testing

- packages/@magic-ext/react-native-bare-oauth/CHANGELOG.md
> Reverse Previous Merge Commit

- packages/@magic-ext/react-native-expo-oauth/CHANGELOG.md
<details>
<br />
```bash
npm install @magic-ext/react-native-expo-oauth@13.4.2-canary.568.5512317306.0
yarn add @magic-ext/react-native-expo-oauth@13.4.2-canary.568.5512317306.0
```
</details>
> Minor change to test merge queuing

- packages/@magic-ext/react-native-expo-oauth/CHANGELOG.md
- packages/@magic-ext/react-native-expo-oauth/package.json
Fixes the version history lost in the previous merge queuing test + removes white space change. 
> Fix RN-Expo-OAuth Version History + Revert Change

- packages/@magic-ext/react-native-bare-oauth/package.json
- packages/@magic-ext/react-native-expo-oauth/package.json
<details>
<br />
```bash
npm install @magic-ext/react-native-bare-oauth@13.4.4-canary.576.5522689634.0
npm install @magic-ext/react-native-expo-oauth@13.4.5-canary.576.5522689634.0
yarn add @magic-ext/react-native-bare-oauth@13.4.4-canary.576.5522689634.0
yarn add @magic-ext/react-native-expo-oauth@13.4.5-canary.576.5522689634.0
``` …
> Update RN OAuth Packages to correct Version

- packages/@magic-ext/react-native-bare-oauth/package.json
- packages/@magic-ext/react-native-expo-oauth/package.json
<details>
<br />
```bash
npm install @magic-ext/react-native-bare-oauth@13.4.5-canary.578.5523775360.0
npm install @magic-ext/react-native-expo-oauth@13.4.6-canary.578.5523775360.0
yarn add @magic-ext/react-native-bare-oauth@13.4.5-canary.578.5523775360.0
yarn add @magic-ext/react-native-expo-oauth@13.4.6-canary.578.5523775360.0
``` …
> Fix RN Verison packages

- packages/@magic-ext/bitcoin/CHANGELOG.md
<details>
<br />
```bash
npm install @magic-ext/bitcoin@13.4.2-canary.577.5524425780.0
yarn add @magic-ext/bitcoin@13.4.2-canary.577.5524425780.0
```
</details>
> Minor update to Changelog to test Deployment Settings

- packages/@magic-ext/solana/CHANGELOG.md
<details>
<br />
```bash
npm install @magic-ext/solana@14.4.2-canary.580.5524468504.0
yarn add @magic-ext/solana@14.4.2-canary.580.5524468504.0
```
</details>
> Minor update to test GH Settings

- packages/@magic-ext/flow/package.json
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/flow@13.5.0-canary.581.5548769405.0
yarn add @magic-ext/flow@13.5.0-canary.581.5548769405.0
```
</details>
> Update flow dependencies

- packages/@magic-sdk/provider/src/modules/nft.ts
- packages/@magic-sdk/types/src/core/json-rpc-types.ts
- Fix invalid API parameter
- Refactor types
<details>
<br />
```bash
npm install @magic-ext/algorand@14.1.1-canary.606.5826677077.0
npm install @magic-ext/aptos@2.1.1-canary.606.5826677077.0
npm install @magic-ext/auth@2.1.1-canary.606.5826677077.0
npm install @magic-ext/avalanche@14.1.1-canary.606.5826677077.0
npm install …
```
> Jayhwang type issues

- packages/@magic-sdk/provider/src/modules/nft.ts
- packages/@magic-sdk/types/src/core/json-rpc-types.ts
- packages/@magic-sdk/types/src/index.ts
- packages/@magic-sdk/types/src/modules/nft-types.ts
- yarn.lock
ref https://github.com/fortmatic/phantom/pull/2917/files
Updating response type for nft.purchase API
<details>
<br />
```bash
npm install @magic-ext/algorand@14.3.1-canary.612.5950631991.0
npm install @magic-ext/aptos@2.3.1-canary.612.5950631991.0
npm install @magic-ext/auth@2.3.1-canary.612.5950631991.0
npm install …
```
> Jayhwang sc 85078 update response type for nft purchase

- packages/@magic-ext/auth/src/index.ts
- packages/@magic-sdk/provider/src/core/sdk-environment.ts
- packages/@magic-sdk/provider/src/core/sdk.ts
- packages/@magic-sdk/provider/src/modules/wallet.ts
- packages/@magic-sdk/provider/test/constants.ts
- packages/@magic-sdk/provider/test/factories.ts
- packages/@magic-sdk/provider/test/spec/core/sdk/constructor.spec.ts
- packages/@magic-sdk/provider/test/spec/modules/nft/transfer.spec.ts
- packages/@magic-sdk/provider/test/spec/modules/wallet/sendGaslessTransaction.spec.ts
- packages/@magic-sdk/react-native-bare/src/index.ts
- packages/@magic-sdk/react-native-expo/src/index.ts
- packages/@magic-sdk/types/src/core/json-rpc-types.ts
- packages/@magic-sdk/types/src/core/query-types.ts
- packages/@magic-sdk/types/src/index.ts
- packages/@magic-sdk/types/src/modules/wallet-types.ts
- packages/magic-sdk/src/index.cdn.ts
- packages/magic-sdk/src/index.ts
added sendGaslessTransaction method
~~added gasEndpoint  to magid-sdk config so that you can test sendGaslessTransaction wherever you want envs~~
removed nftEndpoint
<details>
<br />
```bash
npm install @magic-ext/algorand@14.4.0-canary.622.6178294936.0
npm install @magic-ext/aptos@2.4.0-canary.622.6178294936.0
npm install …
```
> Jayhwang sc 86422 implement magic wallet sendgaslesstxn

- packages/@magic-sdk/provider/src/modules/wallet.ts
- packages/@magic-sdk/provider/test/spec/modules/wallet/sendGaslessTransaction.spec.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/algorand@15.0.1-canary.625.6191564329.0
npm install @magic-ext/aptos@3.0.1-canary.625.6191564329.0
npm install @magic-ext/auth@3.0.1-canary.625.6191564329.0
npm install @magic-ext/avalanche@15.0.1-canary.625.6191564329.0
npm install @magic-ext/bitcoin@15.0.1-canary.625.6191564329.0
npm …
```
> Jayhwang sc 86422 implement magic wallet sendgaslesstxn 2

- packages/@magic-sdk/provider/src/util/web-crypto.ts
- yarn.lock
Optimize webcrypto key generation logic 
<details>
<br />
```bash
npm install @magic-ext/algorand@15.1.0-canary.636.6344998405.0
npm install @magic-ext/aptos@3.1.0-canary.636.6344998405.0
npm install @magic-ext/auth@3.1.0-canary.636.6344998405.0
npm install @magic-ext/avalanche@15.1.0-canary.636.6344998405.0
npm install @magic-ext/bitcoin@15.1.0-canary.636.6344998405.0
npm install …
```
> improve generateKey logic

- packages/@magic-sdk/types/src/modules/auth-types.ts
- yarn.lock
- Specific event type for expired email OTP
<details>
<br />
```bash
npm install @magic-ext/algorand@15.1.1-canary.639.6383552335.0
npm install @magic-ext/aptos@3.1.1-canary.639.6383552335.0
npm install @magic-ext/auth@3.1.1-canary.639.6383552335.0
npm install @magic-ext/avalanche@15.1.1-canary.639.6383552335.0
npm install @magic-ext/bitcoin@15.1.1-canary.639.6383552335.0
npm …
```
> Add expire email OTP to LoginWithEmailOTPEventOnReceived type

- packages/@magic-ext/oauth/package.json
- packages/@magic-ext/oauth/src/crypto.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/oauth@14.1.2-canary.641.6403879697.0
npm install @magic-sdk/pnp@14.1.2-canary.641.6403879697.0
yarn add @magic-ext/oauth@14.1.2-canary.641.6403879697.0
yarn add @magic-sdk/pnp@14.1.2-canary.641.6403879697.0
```
</details>
> Fix crypto-js type

- packages/@magic-ext/solana/package.json
- packages/@magic-ext/solana/src/index.ts
- yarn.lock
Add support for versioned transaction in Solana
<details>
<br />
```bash
npm install @magic-ext/solana@17.2.0-canary.652.6626030981.0
yarn add @magic-ext/solana@17.2.0-canary.652.6626030981.0
```
</details>
> Add support for versioned transaction in Solana

- packages/@magic-ext/solana/src/index.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/solana@17.2.1-canary.660.6804138748.0
yarn add @magic-ext/solana@17.2.1-canary.660.6804138748.0
```
</details>
> Jayhwang sc 90219 signature verification error solana nova

- packages/@magic-ext/react-native-bare-oauth/src/index.ts
- packages/@magic-ext/react-native-expo-oauth/src/index.ts
- yarn.lock
Rename loginWithPopup to loginWithRedirect to match web sdk
<details>
<br />
```bash
npm install @magic-ext/react-native-bare-oauth@17.0.0-canary.663.6853362945.0
npm install @magic-ext/react-native-expo-oauth@17.0.0-canary.663.6853362945.0
npm install @magic-ext/solana@18.0.0-canary.663.6853362945.0
yarn add …
```
> Rename loginWithPopup to loginWithRedirect to match web sdk

- packages/@magic-ext/oidc/README.md
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/oidc@4.4.2-canary.688.7280175520.0
yarn add @magic-ext/oidc@4.4.2-canary.688.7280175520.0
```
</details>
> New token publishing attempt

- package.json
- packages/@magic-ext/oauth2/package.json
- yarn.lock
Fix publishing issue caused by our "auto" package and a known bug it had related to compatibility with our git version. This upgrades to a patch that fixes the issue and unblocks publishing
<details>
<br />
```bash
npm install @magic-ext/oauth2@1.0.0-canary.714.7999646871.0
yarn add @magic-ext/oauth2@1.0.0-canary.714.7999646871.0
```
</details>
> Fixing publishing related to "auto" bug

- packages/@magic-ext/oauth2/README.md
- yarn.lock
Updates OAuth2 readme to use `oauth2` module in example code.
<details>
<br />
```bash
npm install @magic-ext/oauth2@6.0.1-canary.724.8268605606.0
yarn add …
```
> updates readme

- package.json
- yarn.lock
This is a shot in the dark attempt to resolve our issues with auto pushing out `major` releases when labels are marked with `minor` or `patch`. 🤞 
> Update Auto to latest in an attempt to fix versioning error

- .github/workflows/publish.yml
- packages/@magic-ext/oauth/README.md
- yarn.lock
> Pdeexp 681 fix magic js launching script

- .github/workflows/publish.yml
<details>
<br />
```bash
npm install @magic-ext/oauth@22.0.1-canary.730.8396950561.0
npm install @magic-sdk/pnp@22.0.1-canary.730.8396950561.0 …
```
> revert --dry-run

- README.md
- yarn.lock
Readme change for label/patch test
> readme change

- packages/@magic-sdk/provider/README.md
<details>
<br />
```bash
npm install @magic-ext/algorand@23.0.1-canary.732.8397686745.0
npm install …
```
> readme edit

- packages/@magic-sdk/provider/src/modules/user.ts
- packages/@magic-sdk/types/src/core/json-rpc-types.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/algorand@23.0.2-canary.736.8493915852.0
npm install …
```
> rebuild rpc types

- packages/@magic-sdk/provider/src/modules/nft.ts
- packages/@magic-sdk/provider/test/spec/modules/auth/setAuthorizationToken.spec.ts
- packages/@magic-sdk/provider/test/spec/modules/nft/checkout.spec.ts
- packages/@magic-sdk/provider/test/spec/modules/third-party-wallet/getInfo.spec.ts
- packages/@magic-sdk/types/src/modules/intermediary-types.ts
- packages/@magic-sdk/types/src/modules/nft-types.ts
<details>
<br />
```bash
npm install @magic-ext/algorand@23.0.3-canary.744.9317169540.0
npm install …
```
> Jayhwang nft checkout

- packages/@magic-ext/farcaster/src/index.ts
<details>
<br />
```bash
npm install @magic-ext/farcaster@0.0.3-canary.752.9614914380.0
yarn add …
```
> Fix: farcaster mobile login

- packages/@magic-ext/farcaster/src/index.ts
<details>
<br />
```bash
npm install @magic-ext/farcaster@0.0.5-canary.754.9674055381.0
yarn add …
```
> fix: move logic to outside of handle function

- packages/@magic-ext/farcaster/src/index.ts
<details>
<br />
```bash
npm install @magic-ext/farcaster@0.0.6-canary.755.9702407332.0
yarn add …
```
> fix: fix mobile, move channel logic to magic-ext/farcaster

- packages/@magic-ext/farcaster/src/index.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/farcaster@0.1.1-canary.764.9934563820.0
yarn add …
```
> Do not open native farcaster app on mobile

- packages/@magic-ext/farcaster/src/index.ts
- packages/@magic-ext/farcaster/src/utils.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/farcaster@0.2.1-canary.767.9969800718.0
yarn add …
```
> Open native app when mobile, in mainframe

- packages/@magic-sdk/provider/src/modules/auth.ts
- packages/@magic-sdk/provider/test/spec/modules/auth/loginWithEmailOTPWhitelabel.spec.ts
- packages/@magic-sdk/types/src/modules/auth-types.ts
<details>
<br />
```bash
npm install @magic-ext/algorand@23.2.1-canary.770.10283407914.0
npm install …
```
> Added event due to the ticket:PDEEXP-1393

- packages/magic-sdk/src/iframe-controller.ts
- packages/magic-sdk/test/spec/iframe-controller/hideOverlay.spec.ts
- packages/magic-sdk/test/spec/iframe-controller/init.spec.ts
- packages/magic-sdk/test/spec/iframe-controller/showOverlay.spec.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-sdk/pnp@22.3.1-canary.772.10308401329.0
npm install magic-sdk@28.3.1-canary.772.10308401329.0
yarn …
```
> change display css to visibility

- package.json
- packages/@magic-sdk/provider/test/spec/modules/auth/loginWithEmailOTPWhitelabel.spec.ts
Revert Unexpected changes pushed to master
> Revert unexpected master changes

- packages/@magic-ext/cosmos/src/index.ts
- packages/@magic-ext/cosmos/src/type.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/cosmos@23.6.1-canary.801.10779693442.0
yarn add …
```
> cosmos update

- packages/@magic-sdk/types/src/modules/common-types.ts
- packages/@magic-sdk/types/src/modules/intermediary-types.ts
<details>
<br />
```bash
npm install @magic-ext/algorand@23.7.0-canary.805.10800706001.0
npm install …
```
> feat: add UiEventsEmit type

- packages/@magic-ext/cosmos/src/index.ts
- packages/@magic-ext/cosmos/src/type.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/cosmos@23.8.1-canary.807.10816622664.0
yarn add …
```
> fix: move prefix to options, rename

- packages/@magic-ext/cosmos/src/index.ts
- packages/@magic-ext/cosmos/src/type.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/cosmos@23.9.1-canary.809.10836860268.0
yarn add …
```
> add cosmos method

- packages/@magic-sdk/types/src/modules/auth-types.ts
Implement types for disable MFA flow
<details>
<br />
```bash
npm install @magic-ext/algorand@23.10.0-canary.812.10881116112.0
npm install @magic-ext/aptos@11.10.0-canary.812.10881116112.0
npm …
```
> feat: implement disable MFA types

- packages/@magic-sdk/types/src/modules/user-types.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/algorand@23.14.0-canary.821.11409927434.0
npm install …
```
> feat: a new type for malformed phone number

- packages/@magic-sdk/types/src/modules/auth-types.ts
- yarn.lock
> Pdeexp 1951 lost device event does not emit whitelabel mfa

- packages/@magic-sdk/provider/src/modules/user.ts
- packages/@magic-sdk/provider/test/spec/modules/user/showSettings.spec.ts
- packages/@magic-sdk/types/src/modules/user-types.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/algorand@23.14.1-canary.829.11506531330.0
npm install …
```
> fix: cancel event for recovery factor

- packages/@magic-ext/oauth2/src/types.ts
- yarn.lock
https://magiclink.atlassian.net/browse/M2PB-403
https://www.notion.so/magiclabs/Decentraland-OAuth-v2-dynamic-redirect-URIs-132ad65b2b7080e5b349f0584e90c7b8
<details>
<br />
```bash
npm install @magic-ext/oauth2@9.17.1-canary.837.11861508635.0
yarn add @magic-ext/oauth2@9.17.1-canary.837.11861508635.0
```
</details>
> feat: add customData property to OAuthRedirectConfiguration

- packages/@magic-ext/farcaster/src/index.ts
- packages/@magic-sdk/types/src/modules/auth-types.ts
- packages/@magic-sdk/types/src/modules/intermediary-types.ts
<details>
<br />
```bash
npm install @magic-ext/algorand@23.19.0-canary.846.12489063737.0
npm install …
```
> add cancel event to farcaster

- .github/workflows/canary.yml
- .github/workflows/publish.yml
- yarn.lock
Migrates actions/upload-artifact from v3 to v4
Migration instructions: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
> chore: migrate upload-artifact to v4

- packages/@magic-sdk/provider/package.json
- yarn.lock
This version bundles together the changes from `28.21.0` and `28.21.1` into a new major version as the former minor version included breaking changes. These two versions will be marked as deprecated and the changes from them are:
- Removes legacy third party wallet logic
- Adds new web3modal extension which handles the wallet connection request & EIP1193 listeners
- Adds new thirdPartyWallet module which handles isConnected to third party wallet state & rpc routing to wallets
- Updates request function to route payload to third party wallet if connected
- Fixes issue where users were unable to scroll on iOS safari
Please 🚨 **ONLY ADD ONE** 🚨 of the following labels, …
> Major version bump

- packages/@magic-sdk/provider/src/core/sdk-exceptions.ts
- packages/@magic-sdk/provider/src/core/view-controller.ts
- packages/@magic-sdk/types/src/core/exception-types.ts
- packages/magic-sdk/src/iframe-controller.ts
- packages/magic-sdk/test/spec/iframe-controller/_post.spec.ts
* Rework iframe Revival logic
* Extend Interval to 5 mins
* Implement a debouncer to delay the check if iframe is active and being used
* Add logic to check when iframe is removed from the DOM
<details>
<summary>📦 Published PR as canary version: <code>Canary …
> implement checkIframeExists

- packages/@magic-sdk/provider/test/spec/modules/user/isLoggedIn.spec.ts
- scripts/utils/esbuild.ts
- tsconfig.settings.json
> bump target to es 2022

- packages/@magic-sdk/types/src/modules/auth-types.ts
<details>
<br />
```bash
npm install @magic-ext/algorand@24.1.0-canary.889.14908503419.0
npm install …
```
> feat: add login throttled event to email otp

- packages/@magic-sdk/provider/src/modules/third-party-wallets.ts
- packages/@magic-sdk/provider/test/spec/modules/third-party-wallet/getInfo.spec.ts
- packages/@magic-sdk/types/src/modules/user-types.ts
- scripts/bin/wsrun/build-package.ts
<details>
<br />
```bash
npm install @magic-ext/algorand@24.1.0-canary.895.15287114451.0
npm install …
```
> add firstLoginAt

- packages/@magic-ext/aptos/src/constants/index.ts
fixed typos in function inside of packages/@magic-ext/aptos/src/constants/index.ts
none
`patch`
> fix: typos

- packages/@magic-sdk/provider/src/core/sdk.ts
- packages/@magic-sdk/provider/src/modules/base-extension.ts
- packages/@magic-sdk/types/src/modules/auth-types.ts
- scripts/utils/workspace-helpers.ts
> chore: fix some typos in comment

- packages/@magic-sdk/pnp/src/context/callback.ts
- packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
**Description:**
This pull request corrects minor typos in the codebase:
- Fixed the spelling of "directly" in the callback documentation in `callback.ts`.
- Corrected the spelling of "compatible" in a comment in `react-native-webview-controller.tsx`.
> Fix Typos in Documentation and Comments

- packages/@magic-sdk/types/src/modules/user-types.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/algorand@24.2.0-canary.904.16293247371.0
npm install …
```
> feat: implement factors updated event

- packages/@magic-sdk/provider/src/util/web-crypto.ts
- packages/@magic-sdk/provider/test/spec/modules/auth/loginWithMagicLink.spec.ts
- packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
- packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
fix minor issue in the comment
> chore: fix minor issue in the comment

- packages/@magic-ext/harmony/src/types.ts
- yarn.lock
<details>
<br />
```bash
npm install @magic-ext/harmony@24.4.3-canary.927.16976611430.0
yarn add …
```
> removes chainType from harmony config
