magiclabs/magic-js

CHANGELOG.md
src/core/json-rpc.ts
src/modules/base-module.ts
test/spec/core/json-rpc/standardizeJsonRpcRequestPayload.spec.ts

Ethers V5 is using the newly standardized EIP1193 `request` interface, which was causing a conflict with our `BaseModule.request` method. Fortunately, our interface is already on-spec to EIP1193, but we were not doing our standard `payload.id` check on arguments passed to that method.
Testing coming soon!
(Check _one!_)
- #88 
`yarn test`

Patch Ethers V5 beta

---

react-native.d.ts
src/index.cjs.ts
src/index.react-native.ts

It was difficult to get the instance type from the Magic constructor because of our extension wrapping types.
Before, you had to:
```ts
import { Magic } from 'magic-sdk';
const foo: InstanceType<typeof Magic> = new Magic(...);
```
Now, you can just:
```ts
import { Magic } from 'magic-sdk';
const foo: Magic = new Magic(...);
```
(Check _one!_)
- Fixes #91 
`yarn test`

Allow the Magic constructor to also reference the SDK instance type

---

package.json
src/core/payload-transport.ts
src/modules/auth/index.ts
src/modules/base-module.ts
src/modules/rpc-provider/index.ts
src/modules/user/index.ts
src/types/core/message-types.ts
src/util/events.ts
src/util/promise-tools.ts
test/constants.ts
test/spec/modules/base-module/request.spec.ts
test/spec/util/events/createTypedEmitter.spec.ts
test/spec/util/events/typed-emitter/constructor.spec.ts
test/spec/util/promise-tools/createAutoCatchingPromise.spec.ts
test/spec/util/promise-tools/createPromiEvent.spec.ts
test/spec/util/promise-tools/isPromiEvent.spec.ts
yarn.lock

Overloads the promises returned by SDK methods with event emitter methods. This will enable a number of use-cases as described in #93. The events are not yet set up from the iframe side, so we should wait to merge this until that is complete.
(Check _one!_)
- #93 
`yarn test`

PromiEvents

---

packages/web/package.json

We are examining an issue related to Magic SDK extensions related to the usage of `@magic-sdk/provider` and `@magic-sdk/types` as bundled deps instead of external deps.
(Check _one!_)
We'll be testing this as a `canary` version first

Externalize provider and types deps for web entry point

---

package.json
packages/provider/tsconfig.module.json
packages/react-native/package.json
packages/react-native/src/index.ts
packages/react-native/src/react-native-webview-controller.tsx
packages/react-native/test/spec/react-native-webview-controller/postMessage.spec.ts
packages/react-native/tsconfig.module.json
packages/types/tsconfig.module.json
packages/web/src/iframe-controller.ts
packages/web/src/index.ts
packages/web/test/spec/iframe-controller/postMessage.spec.ts
packages/web/tsconfig.cdn.json
packages/web/tsconfig.module.json
scripts/build.sh
scripts/dev.sh
tsconfig.settings.json

This add an explicit `targetOrigin` parameter to `postMessage` calls (before, we used `"*"`).
(Check _one!_)

Add explicit `targetOrigin` parameter to `postMessage` calls

---

packages/provider/package.json
packages/react-native/package.json
packages/types/package.json
packages/web/package.json

A mistake in the `files` array of Package JSON files in the repo lead to a bad deploy. It was fixed in a brute-force way by removing the `files` array completely. This PR replaces that field (in a working condition).

Add 'files' array back to package JSON

---

packages/provider/CHANGELOG.md
packages/provider/src/modules/auth/index.ts
packages/provider/test/spec/modules/auth/loginWithCredential.spec.ts
packages/provider/test/spec/modules/auth/loginWithMagicLink.spec.ts
packages/react-native/CHANGELOG.md
packages/types/CHANGELOG.md
packages/types/src/core/json-rpc-types.ts
packages/types/src/modules/auth-types.ts
packages/web/CHANGELOG.md
scripts/test.sh

This PR adds two features to support redirect URIs in the core magic link flow:
1. Adds `redirectURI` parameter to `loginWithMagicLink`
2. Adds `loginWithCredential` method to support the redirect "callback"
(Check _one!_)

[W.I.P.] Add `redirectURI` parameter to `loginWithMagicLink`; Implement `loginWithCredential`

---

packages/react-native/CHANGELOG.md
packages/react-native/package.json
packages/react-native/src/react-native-transport.ts
yarn.lock

Use `~` to lock dependency versions. Lock `whatwg-url` to `~8.1.0` to prevent usage of `BigInt` which RN env has not supported
(Check _one!_)
- Fixes #131 
Install the latest version

Jerryliu ch25267 missing dependency bigint in react native

---

packages/provider/package.json
packages/provider/src/core/sdk-environment.ts
packages/provider/src/core/sdk-exceptions.ts
packages/provider/src/core/sdk.ts
packages/provider/src/modules/base-extension.ts
packages/provider/test/mocks.ts
packages/provider/test/spec/core/sdk-exceptions/error-factories.spec.ts
packages/provider/test/spec/core/sdk/constructor.spec.ts
packages/types/src/core/exception-types.ts
yarn.lock

Adds a small framework to check Magic SDK extension compatibility at runtime.
(Check _one!_)
- Fixes #122 
`yarn test`

Add framework for extension compatibility checks

---

README.md
packages/commons/README.md
packages/provider/README.md
packages/react-native/README.md
packages/types/README.md
packages/web/README.md
scripts/build.sh
scripts/clean.sh
scripts/dev.sh
scripts/lint.sh
scripts/test.sh
tsconfig.json

This is a simple documentation fix to add changelog links to each package's README file + fixes a typo in the root `tsconfig.json#references`

Fix incorrect TypeScript project references and update READMEs with changelog links

---

packages/commons/package.json
packages/provider/package.json
packages/react-native/package.json
packages/types/package.json
packages/web/package.json
scripts/build.sh
scripts/dev.sh
tsconfig.settings.json
yarn.lock

Adds `importHelpers: true` to our `tsconfig.json` settings to slightly reduce bundle size and suppress `'this' is undefined` warnings from `microbundle`.

Add 'importHelpers: true' to base tsconfig.json

---

packages/provider/src/modules/base-extension.ts
packages/provider/src/modules/base-module.ts

Our usage of ES6 Proxy was breaking support for legacy browsers like IE11. This is a small refactor to remove references to `Proxy`.
`yarn test`, as usual!

Remove ES6 Proxy references

---

packages/types/src/core/exception-types.ts

- https://app.clubhouse.io/magic-labs/story/33482/surface-email-hard-bounce-as-a-user-error-case
Trigger email to a hard bounced email and the sdk should throw error immediately

register "inactive recipient" rpc error code

---

packages/types/src/core/exception-types.ts

With allowlist blocklist we are now supporting a new sdk errors that should be caught by the developer, will be thrown when:
- when an app is private to an email OR
- when the user is explicitly blocked
https://app.clubhouse.io/magic-labs/story/41269/fe-throw-proper-error-when-allow-list-block-list-rules-violated

register access control rpc error code

---

packages/@magic-sdk/provider/package.json
packages/@magic-sdk/provider/src/core/sdk.ts
packages/@magic-sdk/provider/src/modules/rpc-provider.ts
yarn.lock

- https://app.clubhouse.io/magic-labs/story/43477/update-type-signature-of-rpcprovidermodule-to-implement-web3-s-abstractprovider?vc_group_by=day&ct_workflow=all&cf_workflow=500000005
- Fixes #83 

[Feat]: Update type signature of `RpcProviderModule` to implement Web3's `AbstractProvider`

---

packages/@magic-sdk/commons/package.json
packages/@magic-sdk/provider/package.json
packages/@magic-sdk/react-native/package.json
packages/@magic-sdk/types/package.json
packages/magic-sdk/src/index.ts
yarn.lock

Fixes an issue where `regneratorRuntime` may be undefined when importing in modern browsers.

Import regeneratorRuntime in Magic JS (non-CDN version)

---

CONTRIBUTING.md
package.json
packages/@magic-sdk/commons/package.json
packages/@magic-sdk/provider/package.json
packages/@magic-sdk/types/package.json
packages/magic-sdk/package.json
scripts/bin/build.ts
scripts/bin/wsrun/build-package.ts
scripts/utils/microbundle.ts
yarn.lock

Adjusts usage of `"exports"` fields in `package.json` files to point at `modern` and `CJS` compatible bundles [conditionally](https://nodejs.org/api/packages.html#packages_conditional_exports).
- Fixes #213

Fix CJS-dependent entry-points using the 'exports' field in package.json

---

packages/magic-sdk/package.json
scripts/bin/wsrun/build-package.ts
yarn.lock

Fixes an issue where `OAuthExtension` was incompatible with Magic SDK via CDN.

Change 'externals' and 'global' condition in magic-sdk > CDN build

---

packages/@magic-sdk/provider/src/util/index.ts

Removes the (unnecessary) `export * as semver from './semver'` statement in `@magic-sdk/provider/src/utils/index.ts`.
- Fixes #235

Remove 'semver' re-export from '@magic-sdk/provider' utils

---

packages/@magic-ext/oauth/package.json

This fixes the error (below) users on Next.js v12 would run into when starting their app.
```
Cannot find module '/.../node_modules/crypto-js/sha256' imported from /.../node_modules/@magic-ext/oauth/dist/modern/index.mjs
Did you mean to import crypto-js/sha256.js?`
```

move crypto-js to devDependencies to fix bundling error

---

packages/@magic-sdk/types/src/index.ts
packages/magic-sdk/CHANGELOG.md
packages/magic-sdk/src/index.ts

Deprecate test API key
- `major`: Breaking Change: Deprecate test API key

Deprecate test API key

---

.circleci/config.yml

Enables better CI integration for forked PRs by removing the build step which relies on ENV vars.

Update CI to build forked branches without ENV vars

---

packages/@magic-sdk/provider/src/core/sdk-environment.ts
packages/@magic-sdk/provider/src/core/sdk.ts
packages/@magic-sdk/provider/test/spec/core/sdk/constructor.spec.ts
packages/@magic-sdk/react-native/jest.config.ts
packages/@magic-sdk/react-native/package.json
packages/@magic-sdk/react-native/src/index.ts
packages/@magic-sdk/types/src/core/query-types.ts
yarn.lock

Sending bundle iD by using the Expo Application API
This change is a major bump that will completely disable bare-RN use case. 
[SC54819](https://app.shortcut.com/magic-labs/story/54819/earncarrot-whitelist-mobile-app-feature-blocking-users)

Enable bundle Id in Expo

---

packages/@magic-ext/solana/src/index.ts
packages/@magic-ext/solana/src/type.ts

Adds support for signing arbitrary Uint8Array payloads using the user's Solana private key

add signMessage for solana extension

---

packages/@magic-sdk/provider/package.json
packages/@magic-sdk/react-native/README.md
packages/@magic-sdk/react-native/package.json
packages/@magic-sdk/types/package.json
yarn.lock

RN `9.0.0` has been released manually. The manual release skips major upgrades to all packages and only bump major in RN  package.

Update Readme and manual version bump for releases

---

packages/@magic-ext/react-native-oauth/package.json
packages/@magic-ext/react-native-oauth/src/index.ts
yarn.lock

This version bump will get rid of the dependency of unimodules
https://app.shortcut.com/magic-labs/story/57975/react-native-oauth-ext-unimodules-deprecated

bump web-expo-browser version

---

packages/@magic-sdk/types/src/modules/rpc-provider-types.ts

Harryxue sc 61854 m2 magic sdk support goerli testnet and release 

---

packages/@magic-ext/react-native-oauth/README.md
packages/@magic-sdk/react-native/README.md

Adds more context about the use of `expo-web-browser` dependency in  `@magic-ext/react-native-oauth`.
n/a
n/a

Adds more Context about Expo dependency in `@magic-ext/react-native-oauth` to README

---

.github/workflows/publish.yml

This adds the GH_TOKEN to the versioning step in github actions ci, since it is required by `yarn auto version`.

[CHORE] Add gh_token env var to auto version step

---

.github/workflows/publish.yml

Story details: https://app.shortcut.com/magic-labs/story/68022
* remove yarn command in Create Release phase, as it would fail due to a discrepancy in the yarn.lock file after bumping local versions
failed build
https://github.com/magiclabs/magic-js/actions/runs/3842939483/jobs/6544740907
Originally in CircleCI, the command sequence are
```
yarn auto version
yarn lerna version
yarn run build
yarn auto shipit
```
https://app.circleci.com/pipelines/github/magiclabs/magic-js/1242/workflows/bb743c78-9ec1-4acf-9fd6-0cacdfd9c027/jobs/3602

feat: [sc-68022] Fix github action  publishing process in magic-js

---

.github/workflows/publish.yml

This is another shot at getting the `shipit` command to pass cleanly. This utilizes [`--immutable`](https://yarnpkg.com/cli/install) to ensure the lockfile isn't changed.

[CHORE] Resolve shipit release issue

---

.github/workflows/publish.yml

Follow up to fix the [last failing action](https://github.com/magiclabs/magic-js/actions/runs/3849624981/jobs/6558930265). This adds the install step to the publish job, since it is needed before the `shipit` command can complete.

[CHORE ]add install step in publish stage.

---

packages/@magic-ext/react-native-bare-oauth/package.json
packages/@magic-sdk/react-native-bare/README.md
packages/@magic-sdk/react-native-expo/README.md
yarn.lock

Adds `react-native-inappbrowser-reborn` as a peer dependency to our Bare RN OAuth Extension. 
n/a
n/a

Adds react-native-inappbrowser-reborn as peer to Bare RN OAuth

---

packages/@magic-sdk/react-native-bare/README.md
packages/@magic-sdk/react-native-bare/package.json
packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-bare/test/mocks.ts
packages/@magic-sdk/react-native-expo/README.md
packages/@magic-sdk/react-native-expo/package.json
packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-expo/test/mocks.ts
yarn.lock

Replaces the View wrapping the RN SDK package `WebView` with a SafeAreaView to prevent UI overlap with device hardware. 
- Fixes #422 
Using either the [bare](https://github.com/magiclabs/react-native-demo/tree/main/bare/MagicBareRnExample) or [expo](https://github.com/magiclabs/react-native-demo/tree/main/expo/MagicExpoRNExample) sample apps, install either `@magic-sdk/react-native-bare@13.1.1-9591571-2` or `@magic-sdk/react-native-expo@13.1.1-9591571` canary versions. Update [the login method](https://github.com/magiclabs/react-native-demo/blob/main/expo/MagicExpoRNExample/screens/LoginScreen.tsx#L28-L40) to utilize [Magic's SMS login feature](https://magic.link/docs/auth/login-methods/sms/integration/react-native#make-a-request).
- `major`: …

Replaces WebView View wrapper with SafeAreaView

---

packages/@magic-ext/connect/README.md
packages/@magic-ext/connect/package.json
packages/@magic-ext/connect/src/index.ts
yarn.lock

Permits React Native apps to utilize Magic Connect Extension. 
n/a
Utilize [this PR](https://github.com/magiclabs/react-native-demo/pull/17) to test or use either a bare or expo app from [the demos](https://github.com/magiclabs/react-native-demo) and install the canary version of the package via:
```
yarn add @magic-ext/connect@6.2.0-280e018
```
Follow the instructions in the [updated README](https://github.com/magiclabs/magic-js/compare/ariflo-sc-67874-mc-rn-expo?expand=1#diff-27937a4b2ed8380ab55bba3ebd8794b7cc5111d008c4f5660f2a8837a804e747) and verify MC modal opens as illustrated below:

Permit React Native entry to Magic Connect Extension

---

packages/@magic-sdk/react-native-bare/package.json
packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-expo/package.json
packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
yarn.lock

Upgrades our React Native package offerings `react-native-webview` to the latest and utilizes `autoManageStatusBarEnabled` attribute in Webview to prevent style bug.
- Fixes #434 
Utilize expo [demo app](https://github.com/magiclabs/react-native-demo/tree/main/expo/MagicExpoRNExample) and `yarn add @magic-sdk/react-native-expo@14.0.1-903c2bf-2` canary version. Check issue ☝️  for reproduction steps. 

Prevents Relayer from Overriding Status Bar Color

---

packages/@magic-sdk/react-native-bare/package.json
packages/@magic-sdk/react-native-expo/package.json
yarn.lock

Bumps `react-native-webview` peer dependency Requirement to `>=11.0.0`
n/a
n/a

Bumps `react-native-webview` peer dependency Requirement to `>=11.0.0`

---

packages/@magic-sdk/provider/src/core/sdk.ts
packages/@magic-sdk/provider/src/modules/wallet.ts
packages/@magic-sdk/provider/test/spec/modules/wallet/connectWithUI.spec.ts
packages/@magic-sdk/provider/test/spec/modules/wallet/disconnect.spec.ts
packages/@magic-sdk/provider/test/spec/modules/wallet/getInfo.spec.ts
packages/@magic-sdk/provider/test/spec/modules/wallet/requestUserInfoWithUI.spec.ts
packages/@magic-sdk/provider/test/spec/modules/wallet/showUI.spec.ts
packages/@magic-sdk/types/src/core/json-rpc-types.ts
yarn.lock

Move connect methods (& re-named them) to new Wallet module under magic-sdk

move connect methods to wallet module under magic-sdk

---

packages/@magic-ext/bitcoin/package.json
yarn.lock

Removes legacy entry file location for react-native packages to permit React Native SDKs to use Bitcoin extension.
n/a
Utilized Sample RN Demo app in PR https://github.com/magiclabs/react-native-demo/pull/32 as illustrated below:

Permit React Native SDK to Utlize Bitcoin extension

---

packages/@magic-ext/react-native-expo-oauth/package.json
yarn.lock

Updates `expo-web-browser` to the latest to permit higher minimum iOS version supported. 
n/a
n/a

Udpates `expo-web-browser` to the latest for `@magic-ext/react-native-expo-oauth`

---

packages/@magic-sdk/provider/src/modules/user.ts
packages/@magic-sdk/provider/test/spec/modules/user/recoverAccount.spec.ts
packages/@magic-sdk/types/src/core/json-rpc-types.ts
packages/@magic-sdk/types/src/modules/user-types.ts

* Add recoverAccount api

---

packages/@magic-sdk/provider/package.json
packages/@magic-sdk/provider/src/core/sdk-exceptions.ts
packages/@magic-sdk/provider/test/spec/core/sdk-exceptions/magic-rpc-error/constructor.spec.ts
packages/@magic-sdk/provider/test/spec/modules/base-module/request.spec.ts
packages/@magic-sdk/types/src/core/json-rpc-types.ts
yarn.lock

Immutable tested this line of code with 3 providers
- magic provider
- alchemy provider
- json rpc provider
`await contract.connect(PROVIDER).isRegistered(userPublicStarkKey);`
The error from Ethers using the Magic Provider was different than the Alchemy / JSON RPC Providers
This fix makes the error from the Magic Provider consistent with the other providers
Ethers expects a data key to be present in the RPC error - if data is present from bubbled up error, we now map this in the MagicRPCError - see here https://www.jsonrpc.org/specification#response_object
How did you test/validate correctness of changes?
1. Recreate the error in a 3rd party app ([example](https://codesandbox.io/s/magic-stark-contract-bug-prod-3w0zdf?file=/src/App.tsx:1592-1656))
2. Set breakpoints in the ethers library …

Sc 68969 immutable stark error

---

packages/@magic-sdk/react-native-bare/package.json
yarn.lock

`@react-native-community/async-storage` has been deprecated and replaced by `@react-native-async-storage/async-storage`. This updates our dependencies to match the update.
n/a

`@react-native-community/async-storage` => `@react-native-async-storage/async-storage` in RN Bare Package

---

packages/@magic-sdk/react-native-bare/README.md
packages/@magic-sdk/react-native-expo/README.md

Removes the Beta label from our react native packages. 
n/a
n/a
<details>
<br />
```bash
npm install @magic-ext/react-native-bare-oauth@11.2.0-canary.491.4641410358.0
npm install @magic-ext/react-native-expo-oauth@11.2.0-canary.491.4641410358.0
npm install @magic-sdk/react-native-bare@17.2.0-canary.491.4641410358.0
npm install @magic-sdk/react-native-expo@17.2.0-canary.491.4641410358.0
yarn add @magic-ext/react-native-bare-oauth@11.2.0-canary.491.4641410358.0
yarn add …
```

Remove Beta Warning from RN packages

---

packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
yarn.lock

Utilizes `react-native-webview`'s `onShouldStartLoadWithRequest` to detect if a url contains `open_in_device_browser` query and determine if link should be opened on device browser app. 
N/A
Tested the following flow against https://github.com/fortmatic/phantom/pull/2489 update to Relayer with our [React Native Demo Apps](https://github.com/magiclabs/react-native-demo) on iOS and Android. 
<details>
<br />
```bash
npm install @magic-ext/react-native-bare-oauth@12.2.0-canary.507.4930907117.0
npm install …
```

React Native Bare SDK WebView Url Tap Navigate to Device Browser when `open_in_device_browser` is True

---

packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
yarn.lock

Utilizes `react-native-webview`'s `onShouldStartLoadWithRequest` to detect if a url contains `open_in_device_browser` query and determine if link should be opened on device browser app. 
N/A
Tested the following flow against https://github.com/fortmatic/phantom/pull/2489 update to Relayer with our [React Native Demo Apps](https://github.com/magiclabs/react-native-demo) on iOS and Android. 
<details>
<br />
```bash
npm install @magic-ext/react-native-expo-oauth@12.2.0-canary.508.4931052988.0
npm install …
```

React Native Expo SDK WebView Url Tap Navigate to Device Browser when `open_in_device_browser` is True

---

packages/@magic-sdk/provider/src/modules/auth.ts

Adds a `isRNMobilePackage` variable to encourage RN package users to use `auth.loginWithEmailOTP()` instead of the `@magic-ext/auth auth.loginWithMagicLink()` as they will be unable to do so on the next major release. 
n/a
<details>
<br />
```bash
npm install @magic-ext/algorand@12.1.4-canary.518.5018092432.0
npm install @magic-ext/aptos@0.2.1-canary.518.5018092432.0
npm install @magic-ext/auth@0.2.4-canary.518.5018092432.0
npm install …
```

Add conditional for `useInstead` of `loginWithMagicLink` `createDeprecationWarning` call

---

packages/@magic-sdk/provider/src/modules/user.ts
packages/@magic-sdk/provider/test/spec/modules/user/gdkms.spec.ts
packages/@magic-sdk/types/src/core/json-rpc-types.ts
yarn.lock

[Namespace](https://www.notion.so/Kresus-G-DKMS-95d003e6a77248ffb723eb6c1f1157d6?d=d7b173b5fa0747bd9234de4a5af2a6b2#d34e67f20d0640618631dc0781402628)
<details>
<br />
```bash
npm install @magic-ext/algorand@12.2.0-canary.520.5050210538.0
npm install @magic-ext/aptos@0.3.0-canary.520.5050210538.0
npm install @magic-ext/auth@0.3.0-canary.520.5050210538.0
npm install …
```

Add symmetric encryption api

---

packages/@magic-sdk/types/src/core/deep-link-pages.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/algorand@12.2.1-canary.523.5071472728.0
npm install @magic-ext/aptos@0.3.1-canary.523.5071472728.0
npm install @magic-ext/auth@0.3.1-canary.523.5071472728.0
npm install @magic-ext/avalanche@12.2.1-canary.523.5071472728.0
npm install @magic-ext/bitcoin@12.2.1-canary.523.5071472728.0
npm …
```

Add recovery to DeepLink page

---

packages/@magic-ext/aptos/package.json
packages/@magic-ext/aptos/src/MagicAptosWallet.ts
packages/@magic-ext/aptos/src/index.native.ts
yarn.lock

Replace magic-sdk to @magic-sdk/provider for rn support and remove `react-native` filed not used.
Since the aptos-js SDK relies on browser-specific APIs such as TextDecoder and TextEncoder, we need to provide a guideline for installing a text polyfill.
Option 1.
1. Install [react-native-polyfill-globals](https://github.com/acostalima/react-native-polyfill-globals)
```bash
$ yarn add react-native-polyfill-globals text-encoding
```
2. Put the below code into your root file.
```react
import { polyfill as polyfillEncoding } from "react-native-polyfill-globals/src/encoding";
polyfillEncoding();
```
Option 2.
1. Install [text-encoding-polyfill](https://www.npmjs.com/package/text-encoding-polyfill)
```bash
$ yarn add text-encoding-polyfill …
```

Replace magic-sdk to @magic-sdk/provider for rn support

---

jest.config.ts
packages/@magic-ext/auth/src/index.ts
packages/@magic-ext/auth/src/util/version-check.ts
packages/@magic-sdk/provider/src/util/index.ts
packages/@magic-sdk/provider/test/spec/util/isMajorVersionAtLeast.spec.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/algorand@13.0.1-canary.552.5351389326.0
npm install @magic-ext/aptos@1.0.1-canary.552.5351389326.0
npm install @magic-ext/auth@1.0.1-canary.552.5351389326.0
npm install @magic-ext/avalanche@13.0.1-canary.552.5351389326.0
npm install @magic-ext/bitcoin@13.0.1-canary.552.5351389326.0
npm …
```

Fix CI Tests

---

packages/@magic-sdk/provider/test/spec/modules/auth/loginWithMagicLink.spec.ts

Fix Failing CI

---

packages/@magic-sdk/provider/src/modules/nft.ts
packages/@magic-sdk/provider/test/spec/modules/nft/checkout.spec.ts
packages/@magic-sdk/provider/test/spec/modules/nft/purchase.spec.ts
packages/@magic-sdk/types/src/core/json-rpc-types.ts

- Implement view-in-wallet
- https://app.shortcut.com/magic-labs/story/79972/paypal-implement-view-in-wallet
<details>
<br />
```bash
npm install @magic-ext/algorand@13.1.0-canary.548.5359961176.0
npm install @magic-ext/aptos@1.1.0-canary.548.5359961176.0
npm install @magic-ext/auth@1.1.0-canary.548.5359961176.0
npm install …
```

Implement view-in-wallet

---

.github/workflows/canary.yml
yarn.lock

Remove approval step for canary releases
- Fixes #80045
Validate canary release on next merge to master is auto published
<details>
<br />
```bash
npm install @magic-ext/algorand@13.0.1-canary.549.5359900236.0
npm install @magic-ext/aptos@1.0.1-canary.549.5359900236.0
npm install @magic-ext/auth@1.0.1-canary.549.5359900236.0
npm install @magic-ext/avalanche@13.0.1-canary.549.5359900236.0
npm install @magic-ext/bitcoin@13.0.1-canary.549.5359900236.0
npm install @magic-ext/conflux@11.0.1-canary.549.5359900236.0
npm install @magic-ext/cosmos@13.0.1-canary.549.5359900236.0
npm install @magic-ext/ed25519@9.0.1-canary.549.5359900236.0
npm install …
```

Remove approval step for canary releases [sc-80045]

---

packages/@magic-ext/aptos/package.json
packages/@magic-sdk/commons/package.json
packages/@magic-sdk/provider/package.json
packages/@magic-sdk/types/package.json
packages/magic-sdk/package.json

Cannot find types of magic-sdk in vite-react app
- https://github.com/gxmari007/vite-plugin-eslint/pull/60
- https://github.com/moleculerjs/moleculer/pull/1210
Create a new vite-react app with the below commend
```bash
npx vite@latest
```
Install magic-sdk and check if types of magic-sdk is loaded
<details>
<br />
```bash
npm install …
```

Add typings to package.json export

---

packages/@magic-sdk/provider/src/modules/nft.ts
yarn.lock

ref #https://github.com/fortmatic/phantom/pull/2720
After the above PR, we don't need to handle `deeplink` in SDK anymore.
So, I reverted the logic.
<details>
<br />
```bash
npm install @magic-ext/algorand@13.2.1-canary.560.5422742339.0
npm install @magic-ext/aptos@1.2.1-canary.560.5422742339.0
npm install …
```

Revert nft.checkout

---

.github/workflows/test.yml

We need to [trigger `merge_group` checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions) in order to get merge queuing to work. 
N/A

Adds merge_group to Test Workflow

---

.github/workflows/canary.yml
.github/workflows/publish.yml

We need to [trigger `merge_group` checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions) in order to get merge queuing to work. 

Adds merge_group to Canary Workflow

---

packages/@magic-ext/react-native-bare-oauth/CHANGELOG.md
packages/@magic-ext/react-native-bare-oauth/package.json
packages/@magic-ext/react-native-expo-oauth/CHANGELOG.md
packages/@magic-ext/react-native-expo-oauth/package.json

- Fix Version History of RN OAuth Packages
- Test Merge Queuing
<details>
<br />
```bash
npm install @magic-ext/react-native-bare-oauth@13.4.3-canary.574.5513673038.0
npm install @magic-ext/react-native-expo-oauth@13.4.4-canary.574.5513673038.0
yarn add @magic-ext/react-native-bare-oauth@13.4.3-canary.574.5513673038.0
yarn add @magic-ext/react-native-expo-oauth@13.4.4-canary.574.551367303 …
```

Fix Version History of RN OAuth Packages

---

.github/workflows/canary.yml
.github/workflows/publish.yml
packages/@magic-sdk/react-native-bare/package.json
packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-expo/package.json
packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
yarn.lock

Enables WebView Inspection for RN SDKs released in version 12.4 of the library: https://github.com/react-native-webview/react-native-webview/pull/2937
n/a
n/a
<details>
<br />
```bash
npm install @magic-ext/react-native-bare-oauth@13.4.7-canary.587.5626126964.0
npm install @magic-ext/react-native-expo-oauth@13.4.8-canary.587.5626126964.0
npm install @magic-sdk/react-native-bare@19.4.2-canary.587.5626126964.0
npm install @magic-sdk/react-native-expo@19.4.2-canary.587.5626126964.0
yarn add …
```

Enables WebView Inspection for RN SDKs

---

packages/@magic-ext/auth/src/index.ts
packages/@magic-sdk/provider/src/core/sdk-environment.ts
packages/@magic-sdk/provider/src/core/sdk.ts
packages/@magic-sdk/provider/test/constants.ts
packages/@magic-sdk/provider/test/factories.ts
packages/@magic-sdk/provider/test/spec/core/sdk/constructor.spec.ts
packages/@magic-sdk/provider/test/spec/modules/user/getInfo.spec.ts
packages/@magic-sdk/react-native-bare/src/index.ts
packages/@magic-sdk/react-native-expo/src/index.ts
packages/@magic-sdk/types/src/core/query-types.ts
packages/magic-sdk/src/index.cdn.ts
packages/magic-sdk/src/index.ts

Create a magic instance with `nftEnpoint` param so that internal developers point to nft-api endpoint they want 
Add `nftEndpoint` param in SDK config
<details>
<br />
```bash
npm install @magic-ext/algorand@13.5.0-canary.586.5627642781.0
npm install @magic-ext/aptos@1.5.0-canary.586.5627642781.0
npm install …
```

Add optional nftEndpoint param

---

.github/workflows/publish.yml
packages/@magic-sdk/react-native-bare/README.md
packages/@magic-sdk/react-native-bare/package.json
packages/@magic-sdk/react-native-expo/README.md
packages/@magic-sdk/react-native-expo/package.json

Updates Publish GHA Job to permit Git merge queuing
N/A
<details>
<br />
```bash
npm install @magic-ext/algorand@13.4.2-canary.593.5648237905.0
npm install @magic-ext/aptos@1.4.2-canary.593.5648237905.0
npm install @magic-ext/auth@1.4.2-canary.593.5648237905.0
npm install @magic-ext/avalanche@13.4.2-canary.593.5648237905.0
npm install @magic-ext/bitcoin@13.4.3-canary.593.5648237905.0
npm install …
```

Fix Publish GHA Workflow

---

packages/@magic-ext/auth/package.json
scripts/bin/wsrun/build-package.ts
scripts/utils/esbuild.ts
yarn.lock

Similar to what was done on commit https://github.com/magiclabs/magic-js/pull/525/commits/4b3a106681d8745994184b9ed5b1667344399fc2, we need to remove this attribute to permit the extension to work with our RN packages. 
n/a
<details>
<br />
```bash
npm install @magic-ext/auth@1.5.1-canary.595.5673997790.0
yarn add @magic-ext/auth@1.5.1-canary.595.5673997790.0
```
</details>

Remove React-native entry from @magic-ext/auth Package.json

---

packages/@magic-sdk/provider/src/modules/wallet.ts
packages/@magic-sdk/provider/test/spec/modules/wallet/showAddress.spec.ts
packages/@magic-sdk/provider/test/spec/modules/wallet/showBalances.spec.ts
packages/@magic-sdk/provider/test/spec/modules/wallet/showNFTs.spec.ts
packages/@magic-sdk/provider/test/spec/modules/wallet/showOnRamp.spec.ts
packages/@magic-sdk/provider/test/spec/modules/wallet/showSendTokensUI.spec.ts
packages/@magic-sdk/types/src/core/json-rpc-types.ts
yarn.lock

Add deep-linked SDK methods
- `wallet.showAddress`
- `wallet.showSendTokensUI` 
- `wallet.showOnRamp`  
- `wallet.showNFTs` 
- `wallet.showBalances` 
- https://app.shortcut.com/magic-labs/story/79730/new-sdk-method-magic-wallet-showaddress
- https://app.shortcut.com/magic-labs/story/79729/new-sdk-method-magic-wallet-showsendtokens
- https://app.shortcut.com/magic-labs/story/79727/new-sdk-method-magic-wallet-showonramp
- https://app.shortcut.com/magic-labs/story/79726/new-sdk-method-magic-wallet-shownfts
- https://app.shortcut.com/magic-labs/story/79728/new-sdk-method-magic-wallet-showbalances
- `skip-release`: …

Deeplinked wallet methods

---

scripts/bin/dev.ts

Before, when run `yarn dev`, it doesn't watch & rebuild other dependencies when you change dependent files,
After this change, When run `yarn dev` and select `magic-sdk`,
other dependencies also watch and rebuild (e.g. `@magic-sdk/provider`)

[minor] Improve dev.ts script for watch & rebuild dependencies

---

packages/@magic-sdk/provider/src/modules/nft.ts
packages/@magic-sdk/types/src/core/json-rpc-types.ts

<details>
<br />
```bash
npm install @magic-ext/algorand@14.0.1-canary.602.5787985892.0
npm install @magic-ext/aptos@2.0.1-canary.602.5787985892.0
npm install @magic-ext/auth@2.0.1-canary.602.5787985892.0
npm install @magic-ext/avalanche@14.0.1-canary.602.5787985892.0
npm install @magic-ext/bitcoin@14.0.1-canary.602.5787985892.0
npm …
```

Implement nft.transfer api

---

packages/@magic-ext/hedera/package.json
yarn.lock

https://app.shortcut.com/magic-labs/story/77214/blockchain-update-hedera-sdk-package
We need to set peerDependency for hedera so that we can make sure a developer uses over 2.31.0 version
<details>
<br />
```bash
npm install @magic-ext/hedera@1.0.1-canary.604.5820404689.0
yarn add @magic-ext/hedera@1.0.1-canary.604.5820404689.0
``` …

Set peer dependency for hedera

---

packages/@magic-ext/auth/src/index.ts

SDK Environment object was used incorrectly in the extension object.
Also, we can actually remove this check as the gating of redirectUris on mobile is already handled on the relayer side
https://app.shortcut.com/magic-labs/story/82618/authextension-loginwithcredential-broken
<details>
<br />
```bash
npm install @magic-ext/auth@2.2.0-canary.605.5824411184.0
yarn add @magic-ext/auth@2.2.0-canary.605.5824411184.0
```
</details>

no need to check for sdk platform here.

---

packages/@magic-ext/oauth/package.json
packages/@magic-ext/oauth/src/index.ts
yarn.lock

getting a dependency error when trying to import the OAuthExtension module
and it's likely due to us including magic-sdk as a dependency in the extension itself
<details>
<br />
```bash
npm install @magic-ext/oauth@13.3.2-canary.618.6051652890.0
npm install @magic-sdk/pnp@13.3.2-canary.618.6051652890.0
yarn add @magic-ext/oauth@13.3.2-canary.618.6051652890.0
yarn add …
```

import extension from @magic-sdk/commons instead of magick-sdk

---

packages/@magic-ext/oauth/package.json
packages/@magic-ext/oauth/src/crypto.ts
yarn.lock

Update `@magic-ext/oauth` crypto-js dependency due to ES module error in nextjs build.
<details>
<br />
```bash
npm install @magic-ext/oauth@14.0.2-canary.627.6219764474.0
npm install @magic-sdk/pnp@14.0.2-canary.627.6219764474.0
yarn add @magic-ext/oauth@14.0.2-canary.627.6219764474.0
yarn add …
```

Update @magic-ext/oauth crypto-js es module dependency

---

packages/@magic-sdk/provider/src/modules/auth.ts

Removes deprecation warnings from `AuthModule` methods moved to the `@magic-ext/auth` as the extension will be deprecated with the end of support for Universal Wallets. 
n/a
n\a
<details>
<br />
```bash
npm install @magic-ext/algorand@15.0.2-canary.629.6254645033.0
npm install @magic-ext/aptos@3.0.2-canary.629.6254645033.0
npm install @magic-ext/auth@3.0.2-canary.629.6254645033.0
npm install @magic-ext/avalanche@15.0.2-canary.629.6254645033.0
npm install @magic-ext/bitcoin@15.0.2-canary.629.6254645033.0
npm …
```

Removes Deprecation Warnings for`@magic-ext/auth` methods

---

packages/@magic-ext/flow/package.json
yarn.lock

The flow extension was missing a cdnGlobalName in its package.json, preventing it from being imported via CDN. This fixes that.
<details>
<br />
```bash
npm install @magic-ext/flow@15.0.3-canary.630.6265151757.0
yarn add @magic-ext/flow@15.0.3-canary.630.6265151757.0
```
</details>

adds cdnGlobalName to flow package.json

---

BUILD_SYSTEM.md
packages/@magic-ext/algorand/package.json
packages/@magic-ext/avalanche/package.json
packages/@magic-ext/conflux/package.json
packages/@magic-ext/cosmos/package.json
packages/@magic-ext/ed25519/package.json
packages/@magic-ext/flow/package.json
packages/@magic-ext/hedera/package.json
packages/@magic-ext/icon/package.json
packages/@magic-ext/near/package.json
packages/@magic-ext/polkadot/package.json
packages/@magic-ext/solana/package.json
packages/@magic-ext/taquito/package.json
packages/@magic-ext/terra/package.json
packages/@magic-ext/tezos/package.json
packages/@magic-ext/webauthn/package.json
packages/@magic-ext/zilliqa/package.json
yarn.lock

- Removes React Native entrypoint from all extension's package.json
- Fixes https://github.com/magiclabs/react-native-demo/issues/68
<details>
<br />
```bash
npm install @magic-ext/algorand@15.1.2-canary.644.6475639388.0
npm install @magic-ext/avalanche@15.1.2-canary.644.6475639388.0
npm install @magic-ext/conflux@13.1.2-canary.644.6475639388.0
npm install @magic-ext/cosmos@15.1.2-canary.644.6475639388.0
npm install …
```

Removes React Native entrypoint from all extension's package.json

---

packages/@magic-sdk/provider/src/core/sdk.ts
packages/@magic-sdk/provider/test/spec/core/sdk/overlay.spec.ts

Have the SDK constructor run the iframe bootstrap logic by default, and introduce an SDK config flag to defer the preloading for devs who want to control when the Magic Iframe assets get loaded.
- [CH87853](https://app.shortcut.com/magic-labs/story/87853/productionalize-deferpreload-sdk-flag)
`const m = new Magic(API_KEY)` -> will immediately bootstrap the auth relayer iframe by default
`const m = new Magic(API_KEY, { deferPreload: true })` -> will not bootstrap the auth relayer iframe until the first sdk request is made (existing behavior)
<details>
<summary>📦 Published PR as canary version: <code>Canary …

Have the constructor preload iframe assets by default, with optional SDK flag to defer preloading

---

packages/@magic-sdk/provider/src/modules/auth.ts
packages/@magic-sdk/provider/test/spec/modules/auth/loginWithEmailOTP.spec.ts
packages/@magic-sdk/provider/test/spec/modules/auth/loginWithMagicLink.spec.ts
packages/@magic-sdk/types/src/modules/auth-types.ts
yarn.lock

Adds optional template name argument for use with new email customization feature
https://app.shortcut.com/magic-labs/story/87362/sdk-updates
<details>
<br />
```bash
npm install @magic-ext/algorand@16.1.0-canary.643.6567644654.0
npm install @magic-ext/aptos@4.1.0-canary.643.6567644654.0
npm install @magic-ext/auth@4.1.0-canary.643.6567644654.0
npm install @magic-ext/avalanche@16.1.0-canary.643.6567644654.0
npm install …
```

Adds template name to loginWithOTP and loginWithMagicLink

---

packages/@magic-sdk/types/src/modules/nft-types.ts
yarn.lock

Please see the shortcut ticket 
- [Shortcut Story #88513: [NFT Checkout] SDK parameter validation](https://app.shortcut.com/magic-labs/story/88513/nft-checkout-sdk-parameter-validation).
<details>
<br />
```bash
npm install @magic-ext/algorand@16.1.1-canary.649.6573548729.0
npm install @magic-ext/aptos@4.1.1-canary.649.6573548729.0 …
```

Change NFTCheckoutRequest type

---

packages/@magic-sdk/types/src/modules/rpc-provider-types.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/algorand@16.1.2-canary.646.6629426050.0
npm install @magic-ext/aptos@4.1.2-canary.646.6629426050.0
npm install @magic-ext/auth@4.1.2-canary.646.6629426050.0
npm install @magic-ext/avalanche@16.1.2-canary.646.6629426050.0
npm install @magic-ext/bitcoin@16.1.2-canary.646.6629426050.0
npm …
```

allow sepolia for network key

---

packages/@magic-sdk/react-native-bare/README.md
packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
yarn.lock

Fix: Add optional backgroundColor prop to relayer to fix issue with SafeAreaView showing background because it is transparent. Check before/after recordings below.
https://github.com/magiclabs/magic-js/issues/445
https://github.com/magiclabs/magic-js/assets/150072475/ec5afa12-e0b0-4a43-973c-de18aad85d26
https://github.com/magiclabs/magic-js/assets/150072475/80c83b61-685e-4c2f-9b63-1c4414739b7f
<details>
<summary>📦 Published PR as canary version: …

Adds optional backgroundColor prop to Relayer component

---

packages/@magic-ext/solana/src/constants.ts
packages/@magic-ext/solana/src/index.ts
packages/@magic-ext/solana/src/type.ts
yarn.lock

Add types to sign methods to avoid returning 'any' type
<details>
<br />
```bash
npm install @magic-ext/solana@17.2.2-canary.662.6807796828.0
yarn add @magic-ext/solana@17.2.2-canary.662.6807796828.0
```
</details>

Add types to sign methods to avoid returning 'any' type

---

packages/@magic-sdk/provider/src/core/sdk.ts
packages/@magic-sdk/provider/src/core/view-controller.ts
packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts
packages/@magic-sdk/react-native-bare/README.md
packages/@magic-sdk/react-native-bare/jest.config.ts
packages/@magic-sdk/react-native-bare/package.json
packages/@magic-sdk/react-native-bare/src/hooks.ts
packages/@magic-sdk/react-native-bare/src/index.ts
packages/@magic-sdk/react-native-bare/test/mocks.ts
packages/@magic-sdk/react-native-bare/test/spec/hooks.spec.ts
packages/@magic-sdk/react-native-expo/README.md
packages/@magic-sdk/react-native-expo/jest.config.ts
packages/@magic-sdk/react-native-expo/package.json
packages/@magic-sdk/react-native-expo/src/hooks.ts
packages/@magic-sdk/react-native-expo/src/index.ts
packages/@magic-sdk/react-native-expo/test/mocks.ts
packages/@magic-sdk/react-native-expo/test/spec/hooks.spec.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/algorand@16.3.0-canary.665.6934462457.0
npm install @magic-ext/aptos@4.3.0-canary.665.6934462457.0
npm install @magic-ext/auth@4.3.0-canary.665.6934462457.0
npm install @magic-ext/avalanche@16.3.0-canary.665.6934462457.0
npm install @magic-ext/bitcoin@16.3.0-canary.665.6934462457.0
npm …
```

Add `useInternetConnection` hook to track internet connectivity changes

---

packages/@magic-ext/react-native-bare-oauth/src/index.ts
packages/@magic-ext/react-native-expo-oauth/src/index.ts
yarn.lock

This reverts commit 09ec3931
<details>
<br />
```bash
npm install @magic-ext/react-native-bare-oauth@18.0.0-canary.668.6937289924.0
npm install @magic-ext/react-native-expo-oauth@18.0.0-canary.668.6937289924.0
yarn add @magic-ext/react-native-bare-oauth@18.0.0-canary.668.6937289924.0
yarn add …
```

Revert "Rename: ready -> checkIsReadyForRequest and isReady -> isReadyForRequest"

---

packages/@magic-ext/algorand/package.json
packages/@magic-ext/auth/package.json
packages/@magic-ext/avalanche/package.json
packages/@magic-ext/bitcoin/package.json
packages/@magic-ext/conflux/package.json
packages/@magic-ext/cosmos/package.json
packages/@magic-ext/ed25519/package.json
packages/@magic-ext/flow/package.json
packages/@magic-ext/gdkms/package.json
packages/@magic-ext/harmony/package.json
packages/@magic-ext/hedera/package.json
packages/@magic-ext/icon/package.json
packages/@magic-ext/near/package.json
packages/@magic-ext/oauth/package.json
packages/@magic-ext/oidc/package.json
packages/@magic-ext/polkadot/package.json
packages/@magic-ext/react-native-bare-oauth/package.json
packages/@magic-ext/react-native-expo-oauth/package.json
packages/@magic-ext/taquito/package.json
packages/@magic-ext/terra/package.json
packages/@magic-ext/tezos/package.json
packages/@magic-ext/webauthn/package.json
packages/@magic-ext/zilliqa/package.json

This PR updates the `package.json` files for all of the `@magic-ext` packages (apart from aptos and solana, which already had this change applied).
This is essentially the same change that has already been applied in https://github.com/magiclabs/magic-js/pull/517 by @octave08 (why wasn't this done for all packages?) and proposed in https://github.com/magiclabs/magic-js/pull/626
Fixes #669 
Create a new TypeScript web app that uses `node16` or `nodenext` module resolution, try to import these packages, TypeScript should be able to perform type checking based on the types of the imported objects.

Fix TypeScript resolution for @magic-ext/* packages when using modern module resolution (node16 etc)

---

scripts/bin/scaffold/template/hybrid/package.json
scripts/bin/scaffold/template/react-native/package.json
scripts/bin/scaffold/template/web/package.json
yarn.lock

Our scaffolding templates did not have a `types` export. This caused many of our extensions to not have this export in their `package.json`'s.
- Add `types` export to each template scaffolding

add types to scaffolding export

---

packages/@magic-sdk/provider/src/core/view-controller.ts
packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts
packages/@magic-sdk/react-native-bare/package.json
packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-expo/package.json
packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx

Fix: Allow classes that extend `view-controller` to set if it's connected to the internet, and reject requests when `isConnectedToInternet` is `false`.
On mobile, it takes a while for the connectivity to the overlay to be established. If a method like `isLoggedIn` is called before that (i.e. on app start-up), it would reject it, which is not ideal. This fix allows you to call methods like `isLoggedIn` even before the connection is established, and wait for a response.
Fixes https://github.com/magiclabs/magic-js/issues/672
- `skip-release`: It's unnecessary to …

Fix: Allow implementers of `view-controller` to set if it's connected to the internet, and reject requests when `isConnectedToInternet` is `false`

---

packages/@magic-ext/solana/src/index.ts

<details>
<br />
```bash
npm install @magic-ext/solana@18.3.0-canary.691.7291625982.0
yarn add @magic-ext/solana@18.3.0-canary.691.7291625982.0
```
</details>

Fix type mismatch for signMessage in solana-ext

---

packages/@magic-ext/oauth/package.json

Fix webpack 5 build fail for magic-ext/oauth
<details>
<br />
```bash
npm install @magic-ext/oauth@15.4.2-canary.692.7296356209.0
npm install @magic-ext/solana@18.2.2-canary.692.7296356209.0
npm install @magic-sdk/pnp@15.4.2-canary.692.7296356209.0
yarn add @magic-ext/oauth@15.4.2-canary.692.7296356209.0
yarn add @magic-ext/solana@18.2.2-canary.692.7296356209.0
yarn add …
```

move crypto-js to dependencies

---

packages/@magic-ext/oauth/src/crypto.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/oauth@15.5.1-canary.694.7332577917.0
npm install @magic-sdk/pnp@15.5.1-canary.694.7332577917.0
yarn add @magic-ext/oauth@15.5.1-canary.694.7332577917.0
yarn add @magic-sdk/pnp@15.5.1-canary.694.7332577917.0
```
</details>

Fix: use default import of crypto-js to fix unresolved imports after build

---

packages/@magic-sdk/provider/src/core/sdk.ts
packages/@magic-sdk/types/src/core/query-types.ts
yarn.lock

Adding a meta field to the Magic constructor in the @magic-sdk package to allow arbitrary data to be sent to the Magic backend. Ping @bengriffin1 for more details.
n/a
No test needed as of now
<details>
<br />
```bash
npm install @magic-ext/algorand@17.1.0-canary.708.7845477243.0
npm install @magic-ext/aptos@5.1.0-canary.708.7845477243.0
npm install @magic-ext/avalanche@17.1.0-canary.708.7845477243.0
npm install @magic-ext/bitcoin@17.1.0-canary.708.7845477243.0
npm install …
```

[FEAT]: adding meta field to @magic-sdk magic constructor

---

packages/@magic-sdk/types/src/modules/auth-types.ts
yarn.lock

[Ticket here](https://magiclink.atlassian.net/jira/software/c/projects/PDEEXP/boards/10?assignee=712020%3Aa5d1156c-55c5-428f-b5c1-7e50a31a58fd&selectedIssue=PDEEXP-253)
WalletConnect needed an additional event for the updateEmail whitelabel flow to account for an email address already being in use.
- Adds additional event
<details>
<br />
```bash
npm install @magic-ext/algorand@17.1.1-canary.709.7850491789.0
npm install …
```

updateEmail: Adds event for email already exists

---

packages/@magic-sdk/provider/src/core/sdk-exceptions.ts
packages/@magic-sdk/provider/test/spec/core/sdk-exceptions/error-factories.spec.ts
packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts
packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-bare/test/spec/react-native-webview-controller/_post.spec.ts
packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-expo/test/spec/react-native-webview-controller/_post.spec.ts
packages/@magic-sdk/types/src/core/exception-types.ts
yarn.lock

Adds a Response Timeout Error to our RN SDKs. See [PDEEXP-233](https://magiclink.atlassian.net/browse/PDEEXP-233?atlOrigin=eyJpIjoiMDI4ODdiMGE3NGQxNDcwNWI2OGYyNjZmY2ViODNlZGEiLCJwIjoiaiJ9) for details.
n/a
[PDEEXP-233]: https://magiclink.atlassian.net/browse/PDEEXP-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

Adds Response Time out Error to RN SDKs

---

packages/@magic-sdk/provider/src/core/sdk-exceptions.ts
packages/@magic-sdk/provider/test/spec/core/sdk-exceptions/error-factories.spec.ts
packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts
packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-bare/test/spec/react-native-webview-controller/_post.spec.ts
packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-expo/test/spec/react-native-webview-controller/_post.spec.ts
packages/@magic-sdk/types/src/core/exception-types.ts

Reverts PR https://github.com/magiclabs/magic-js/pull/721 which would throw a response timeout when a user's device connectivity is slow. 
n/a
<details>
<br />
```bash
npm install @magic-ext/algorand@21.1.0-canary.725.8302989803.0
npm install …
```

Reverts - Adds Response Time out Error to RN SDKs

---

packages/@magic-sdk/provider/test/spec/modules/nft/checkout.spec.ts
packages/@magic-sdk/types/src/modules/nft-types.ts

- Added an option for crypto-checkout
- Updated nft-response status
<details>
<br />
```bash
npm install …
```

Add an option for crypto-checkout

---

packages/@magic-sdk/types/src/modules/auth-types.ts
packages/@magic-sdk/types/src/modules/wallet-types.ts

Add two more events for better UX
<details>
<br />
```bash
npm install @magic-ext/algorand@23.0.3-canary.746.9405081585.0
npm install …
```

Add two more events for EmailOTP

---

packages/@magic-sdk/types/src/modules/intermediary-types.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/algorand@23.0.4-canary.748.9407252911.0
npm install …
```

Pdeexp 1279 done event not firing in whitelabel email login flow

---

packages/@magic-sdk/types/src/modules/intermediary-types.ts
packages/@magic-sdk/types/src/modules/nft-types.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/algorand@23.0.5-canary.749.9420981984.0
npm install …
```

update intermediary types

---

packages/@magic-sdk/types/src/modules/auth-types.ts
packages/@magic-sdk/types/src/modules/intermediary-types.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/algorand@23.0.6-canary.751.9562340473.0
npm install …
```

Add farcaster event types

---

package.json
packages/@magic-ext/farcaster/package.json
packages/@magic-ext/farcaster/src/index.ts
scripts/bin/lint.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/farcaster@0.0.7-canary.758.9780606179.0
yarn add …
```

fix: remove farcaster deps

---

packages/@magic-sdk/provider/src/core/view-controller.ts
packages/@magic-sdk/provider/test/spec/core/view-controller/waitForReady.spec.ts

We expect the overlay to be ready within 15 seconds. Sometimes the message is not properly processed due to webview issues. In that case, after 15 seconds we consider the overlay ready, to avoid requests hanging forever.
<details>
<br /> …

Fix: consider the provider ready after 15s even if the message hasn't arrived

---

packages/@magic-ext/solana/src/index.ts

<details>
<br />
```bash
npm install @magic-ext/solana@25.2.1-canary.765.9948183993.0
yarn add @magic-ext/solana@25.2.1-canary.765.9948183993.0
```
</details>

fix: partialSignTransaction return type is Uint8Array

---

packages/@magic-sdk/provider/src/modules/wallet.ts
packages/@magic-sdk/provider/test/spec/modules/wallet/showUI.spec.ts

<details>
<br />
```bash
npm install @magic-ext/algorand@23.2.0-canary.766.9964959341.0
npm install …
```

feat: add onramperParams arg to showUI

---

packages/@magic-ext/oauth/src/index.ts
packages/@magic-ext/oauth/src/types.ts
packages/@magic-ext/oauth2/src/index.ts
packages/@magic-ext/oauth2/src/types.ts
packages/@magic-ext/react-native-bare-oauth/src/index.ts
packages/@magic-ext/react-native-bare-oauth/src/types.ts
packages/@magic-ext/react-native-expo-oauth/src/index.ts
packages/@magic-ext/react-native-expo-oauth/src/types.ts
packages/@magic-sdk/provider/src/modules/auth.ts
packages/@magic-sdk/provider/test/spec/modules/auth/loginWithCredential.spec.ts
packages/@magic-sdk/types/src/modules/auth-types.ts

<details>
<br />
```bash
npm install @magic-ext/algorand@23.2.1-canary.771.10218394164.0
npm install …
```

add lifespan parameter to login methods

---

packages/@magic-sdk/provider/src/modules/wallet.ts
packages/@magic-sdk/provider/src/util/promise-tools.ts
packages/@magic-sdk/types/src/core/json-rpc-types.ts

<details>
<br />
```bash
npm install @magic-ext/algorand@23.2.1-canary.773.10246759191.0
npm install …
```

feat: Added new event type in order to prevent typescript error

---

packages/@magic-sdk/types/src/modules/auth-types.ts
packages/@magic-sdk/types/src/modules/intermediary-types.ts

<details>
<br />
```bash
npm install @magic-ext/algorand@23.3.0-canary.777.10283995228.0
npm install …
```

Add new types for whitelabel sms 

---

packages/@magic-sdk/provider/src/util/promise-tools.ts
packages/@magic-sdk/types/src/modules/user-types.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/algorand@23.5.0-canary.781.10422812712.0
npm install …
```

feat: added new event for controlling close by user

---

packages/magic-sdk/src/iframe-controller.ts
packages/magic-sdk/test/spec/iframe-controller/hideOverlay.spec.ts

fix: on iOS Safari it shows a white screen when using display: 'block', visibility: 'hidden'
https://github.com/magiclabs/magic-js/issues/787
<details>
<br />
```bash
npm install @magic-ext/algorand@23.5.1-canary.788.10682754855.0
npm install @magic-ext/aptos@11.5.1-canary.788.10682754855.0
npm install @magic-ext/avalanche@23.5.1-canary.788.10682754855.0
npm install @magic-ext/bitcoin@23.5.1-canary.788.10682754855.0
npm install @magic-ext/conflux@21.5.1-canary.788.10682754855.0
npm install @magic-ext/cosmos@23.5.1-canary.788.10682754855.0
npm install @magic-ext/ed25519@19.5.1-canary.788.10682754855.0
npm install @magic-ext/farcaster@0.5.1-canary.788.10682754855.0
npm …
```

fix: on iOS Safari it shows a white screen when using display: 'block', visibility: 'hidden'

---

packages/@magic-sdk/react-native-bare/package.json
packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-bare/test/setup.ts
packages/@magic-sdk/react-native-bare/test/spec/react-native-webview-controller/_post.spec.ts
packages/@magic-sdk/react-native-expo/package.json
packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-expo/test/setup.ts
packages/@magic-sdk/react-native-expo/test/spec/react-native-webview-controller/_post.spec.ts
yarn.lock

After a period of inactivity, especially when the app goes to the background, iOS will randomly decide to kill the webview process without letting us know in any way. When the user comes back to the app and a magic method is called like `isLoggedIn`, we call `webview.postMessage` but even though the webview process is killed, no error is thrown here.
As a result, the message is never sent to mgbox/mandrake, and the user is left hanging for the response forever. They would need to restart the app for magic to work again.
In this PR, we're checking before posting any message if there's been inactivity. Inactivity is determined when a message is being sent 5 minutes or more after the last sent message.
If inactivity is determined, we briefly unmount and re-mount the webview to force a …

fix: remount the webview after inactivity before posting a message to avoid timeouts

---

packages/@magic-sdk/types/src/index.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/algorand@23.8.0-canary.806.10814729012.0
npm install …
```

fix: export common types

---

packages/@magic-sdk/types/src/modules/auth-types.ts
yarn.lock

Implemented new events for MFA whitelabel
<details>
<br />
```bash
npm install @magic-ext/algorand@23.9.0-canary.803.10817060929.0
npm install @magic-ext/aptos@11.9.0-canary.803.10817060929.0
npm …
```

feat: implement new events for MFA whitelabel

---

packages/@magic-sdk/provider/src/modules/user.ts
packages/@magic-sdk/provider/test/spec/modules/user/mfa.spec.ts
packages/@magic-sdk/types/src/modules/auth-types.ts
packages/@magic-sdk/types/src/modules/intermediary-types.ts
yarn.lock

In this PR I am adding new handlers to enableMFA method
- Enable MFA - https://drive.google.com/file/d/1Fm04Qr70XRIPdN6A7CqPhyTKODmrYRbA/view?usp=drive_link
- Disable MFA with TOTP - https://drive.google.com/file/d/1j3g4VxtXUZFTUfhvNHDxx0EBEc-Ei9cZ/view?usp=sharing
- Disable MFA with Recovery code - https://drive.google.com/file/d/1U9zy0C8cHkVtrYao-YBZMezrnYwM4BId/view?usp=sharing
Please avoid adding any of the `Priority` labels …

White label support for MFA | Should not be merged before Mandrake

---

packages/@magic-sdk/provider/src/modules/auth.ts
packages/@magic-sdk/provider/src/modules/user.ts
packages/@magic-sdk/provider/test/spec/modules/user/showSettings.spec.ts
packages/@magic-sdk/types/src/modules/auth-types.ts
packages/@magic-sdk/types/src/modules/intermediary-types.ts
packages/@magic-sdk/types/src/modules/user-types.ts

<details>
<br />
```bash
npm install @magic-ext/algorand@23.13.0-canary.818.11406806026.0
npm install …
```

feat: recovery facto whitelabeling

---

packages/@magic-sdk/types/src/modules/auth-types.ts

feat: add invalid-recovery-code type to loginWithEmailOtp

---

packages/@magic-sdk/provider/src/modules/user.ts
packages/@magic-sdk/provider/test/spec/modules/user/recoverAccount.spec.ts
packages/@magic-sdk/types/src/modules/intermediary-types.ts
packages/@magic-sdk/types/src/modules/user-types.ts
yarn.lock

https://magiclink.atlassian.net/browse/PDEEXP-1544
<details>
<br />
```bash
npm install @magic-ext/algorand@23.17.0-canary.832.11709014109.0
npm install …
```

Pdeexp 1544 implement magic auth recover account provider

---

BUILD_SYSTEM.md
CONTRIBUTING.md

fix: typos

---

packages/@magic-ext/farcaster/src/index.ts

<details>
<br />
```bash
npm install @magic-ext/algorand@23.18.1-canary.841.12162160785.0
npm install …
```

farcaster login channel reuse

---

packages/@magic-ext/oauth2/src/index.ts
packages/@magic-ext/oauth2/src/types.ts

https://magiclink.atlassian.net/browse/PDEEXP-1958
<details>
<br />
```bash
npm install @magic-ext/oauth2@9.19.0-canary.843.12273572894.0
yarn add @magic-ext/oauth2@9.19.0-canary.843.12273572894.0 …
```

feat: implement seamless telegram login

---

packages/@magic-sdk/provider/src/core/view-controller.ts
packages/@magic-sdk/provider/test/spec/core/view-controller/waitForReady.spec.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/algorand@24.0.1-canary.861.13705391022.0
npm install …
```

remove 15s auto success

---

packages/@magic-ext/oauth2/src/index.ts
packages/@magic-ext/oauth2/src/types.ts
yarn.lock

Add return public address flag to remove the need of returning DID Token in the response
<details>
<br />
```bash
npm install …
```

add skipDIDToken to magic.oauth.getRedirectResult

---

packages/@magic-ext/oauth/package.json
packages/@magic-ext/oauth/src/crypto.ts
packages/@magic-ext/oauth2/package.json
packages/@magic-ext/react-native-bare-oauth/package.json
packages/@magic-ext/react-native-bare-oauth/src/crypto.ts
packages/@magic-ext/react-native-expo-oauth/package.json
packages/@magic-ext/react-native-expo-oauth/src/crypto.ts
yarn.lock

This bumps crypto-js dependency to the latest
<details>
<br />
```bash
npm install @magic-ext/oauth@23.1.0-canary.864.14042819872.0
npm install …
```

bump crypto-js

---

.github/workflows/canary.yml
.github/workflows/publish.yml
.github/workflows/test.yml
packages/@magic-sdk/provider/src/core/view-controller.ts
packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts
packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
packages/magic-sdk/src/iframe-controller.ts
yarn.lock

Fix an edge case where iframe.contentWindow is empty
<details>
<br />
```bash
npm install @magic-ext/algorand@24.0.4-canary.870.14203885986.0 …
```

add iframe.contentWindow check

---

packages/@magic-sdk/provider/src/core/json-rpc.ts
packages/@magic-sdk/provider/src/modules/auth.ts
packages/@magic-sdk/provider/src/modules/base-module.ts
packages/@magic-sdk/provider/src/util/web-crypto.ts
packages/@magic-sdk/types/src/core/exception-types.ts

<details>
<br />
```bash
npm install @magic-ext/algorand@24.1.0-canary.886.14723677664.0
npm install …
```

feat: handle dpop error

---

packages/magic-sdk/README.md

Fixed incorrect relative path to @magic-ext packages in magic-sdk README.md.
Changed from ./packages/@magic-ext to ../@magic-ext to properly reference
the @magic-ext directory from the magic-sdk package context.
This resolves the broken link that was causing file not found errors.

fix: correct @magic-ext packages link in magic-sdk README

---

packages/@magic-ext/aptos/src/index.ts

fixed typo from generateRawTransactionWihtTypedPayload to generateRawTransactionWithTypedPayload

chore: fix typos in function name

---

.husky/pre-commit
packages/@magic-sdk/provider/src/core/sdk.ts
packages/@magic-sdk/provider/src/modules/base-extension.ts
yarn.lock

<details>
<br />
```bash
npm install @magic-ext/algorand@24.4.1-canary.914.16661411429.0
npm install …
```

remove instance of Extension check

---

packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts

Fixed a spelling error in test case descriptions within the post controller test file.
- **File:** `packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts`
- **Lines:** 105, 287
- **Fix:** Corrected "recieves" to "receives" in two test descriptions

 fix typo in test descriptions

---

packages/@magic-sdk/pnp/README.md

Replaced outdated documentation URL in packages/@magic-sdk/pnp/README.md with the updated link to the customization guide for the Login UI.

docs: update Magic Login Form documentation link

---

packages/@magic-ext/webauthn/src/types.ts
packages/magic-sdk/src/iframe-controller.ts
scripts/utils/esbuild.ts

- Corrected "webauth" → "webauthn" in type definition docstring.  
- Clarified iframe reload comment in `IframeController`.  
- Fixed typo "ephermeral" → "ephemeral" in build utils docstring.

docs: fix typos and improve comments across packages

---

packages/@magic-sdk/types/src/modules/auth-types.ts

- Corrected "Decenteralized" → "Decentralized" in multiple interfaces
- Fixed grammar: "will only be affect" → "will only be affected"

docs(types): fix typos in auth-types comments

---

packages/@magic-sdk/react-native-bare/README.md
packages/@magic-sdk/react-native-expo/README.md

fixed broken link
broken: https://magic.link/docs/auth/login-methods/email/email-link-update-march-2023
correct: https://magic.link/docs/authentication/login/magic-links

docs: fix broken link
